class InterfaceError(Exception): ...

class PostgresError(Exception): ...

class PostgresConnectionError(PostgresError): ...

class ConnectionDoesNotExistError(PostgresConnectionError): ...

class OperatorInterventionError(PostgresError): ...

class CannotConnectNowError(OperatorInterventionError): ...
