repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      # Lint using project configuration (pyproject.toml)
      - id: ruff-check
        name: ruff
        args: [--fix]
        stages: [commit]
        files: ^backend/
