repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      # Critical checks (will block commits)
      - id: ruff-check
        name: ruff-critical
        args: [--select, "F401,F811,F821,F841,B007,B008", --fix]
        stages: [commit]
      
      # Auto-format (will fix automatically)  
      - id: ruff-format
        name: ruff-format
        stages: [commit]
        
      # Style checks (warnings only)
      - id: ruff-check
        name: ruff-style
        args: [--select, "E,W,I,UP,B", --ignore, "F401,F811,F821,F841,B007,B008", --fix]
        stages: [commit]
        verbose: true