version: '3'

dotenv: [".env"]

tasks:
  run:
    cmds:
      - uv run start
    dir: ./backend

  worker:
    cmds:
      - uv run arq src.intric.worker.arq.WorkerSettings
    dir: ./backend

  frontend:
    cmds:
      - npm run dev
    dir: ./frontend

  migrate:
    cmds:
      - uv run alembic upgrade head
    dir: ./backend
