/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/eneo-theme.ts
 * Command: astryx theme build src/theme/eneo-theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

import { neutralIconRegistry } from '@astryxdesign/theme-neutral/built';
/**
 * eneo theme — built by `bunx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { eneoTheme } from './eneo';
 *   import './eneo.css';
 */
export const eneoTheme = {
  name: 'eneo',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "var(--font-figtree, Figtree), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "var(--font-figtree, Figtree), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "var(--font-jetbrains-mono, \"JetBrains Mono\"), ui-monospace, \"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#6b187c, #efa8ff)",
    "--color-syntax-string": "light-dark(#0b5615, #a4d6a3)",
    "--color-syntax-comment": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-number": "light-dark(#733100, #ffb37e)",
    "--color-syntax-function": "light-dark(#00458c, #a1caff)",
    "--color-syntax-type": "light-dark(#6b187c, #efa8ff)",
    "--color-syntax-variable": "light-dark(#111111, #e2e2e2)",
    "--color-syntax-operator": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-constant": "light-dark(#733100, #ffb37e)",
    "--color-syntax-tag": "light-dark(#8a0011, #ffaea7)",
    "--color-syntax-attribute": "light-dark(#584400, #eec448)",
    "--color-syntax-property": "light-dark(#005348, #90d7c8)",
    "--color-syntax-punctuation": "light-dark(#6a6a6a, #9e9e9e)",
    "--color-syntax-background": "light-dark(#ffffff, #111111)",
    "--color-background-surface": "light-dark(#FFFFFF, #111419)",
    "--color-background-body": "light-dark(#ECEEF2, #07080B)",
    "--color-background-card": "light-dark(#FFFFFF, #161A20)",
    "--color-background-popover": "light-dark(#FFFFFF, #1C2027)",
    "--color-background-muted": "light-dark(#F2F3F6, #1C2027)",
    "--color-accent": "light-dark(#1A6FD2, #4D94F2)",
    "--color-accent-muted": "light-dark(#E6EEFA, rgba(77, 148, 242, 0.16))",
    "--color-neutral": "light-dark(rgba(15, 18, 23, 0.07), rgba(255, 255, 255, 0.08))",
    "--color-overlay": "light-dark(rgba(15, 18, 23, 0.4), rgba(0, 0, 0, 0.6))",
    "--color-overlay-hover": "light-dark(rgba(15, 18, 23, 0.045), rgba(255, 255, 255, 0.05))",
    "--color-overlay-pressed": "light-dark(rgba(15, 18, 23, 0.09), rgba(255, 255, 255, 0.1))",
    "--color-text-primary": "light-dark(#0F1217, #F1F3F6)",
    "--color-text-secondary": "light-dark(#535A67, #AEB5C1)",
    "--color-text-disabled": "light-dark(#9AA0AB, #5C6470)",
    "--color-text-accent": "light-dark(#1557A8, #8DBAF7)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#111111",
    "--color-on-accent": "light-dark(#FFFFFF, #06101C)",
    "--color-on-success": "light-dark(#FFFFFF, #06101C)",
    "--color-on-error": "light-dark(#FFFFFF, #06101C)",
    "--color-on-warning": "light-dark(#FFFFFF, #06101C)",
    "--color-icon-accent": "light-dark(#1A6FD2, #4D94F2)",
    "--color-icon-primary": "light-dark(#0F1217, #F1F3F6)",
    "--color-icon-secondary": "light-dark(#6B7280, #8B93A1)",
    "--color-icon-disabled": "light-dark(#9AA0AB, #5C6470)",
    "--color-success": "light-dark(#1E7A32, #6CC382)",
    "--color-error": "light-dark(#B42330, #FF8177)",
    "--color-warning": "light-dark(#8A5A00, #E9B949)",
    "--color-success-muted": "light-dark(#E2F2E5, rgba(108, 195, 130, 0.15))",
    "--color-error-muted": "light-dark(#FBE5E6, rgba(255, 129, 119, 0.15))",
    "--color-warning-muted": "light-dark(#FCF0D4, rgba(233, 185, 73, 0.15))",
    "--color-border": "light-dark(rgba(15, 18, 23, 0.09), rgba(255, 255, 255, 0.08))",
    "--color-border-emphasized": "light-dark(#D3D7DE, #2C323B)",
    "--color-skeleton": "light-dark(#E6E9EE, #242A32)",
    "--color-shadow": "light-dark(rgba(0, 0, 0, 0.08), rgba(0, 0, 0, 0.4))",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-red": "light-dark(#FBE5E6, rgba(255, 129, 119, 0.15))",
    "--color-border-red": "light-dark(#ffaea7, #fa6762)",
    "--color-icon-red": "light-dark(#B42330, #FF8177)",
    "--color-text-red": "light-dark(#B42330, #FF8177)",
    "--color-background-orange": "light-dark(#FBEEDB, rgba(241, 180, 92, 0.14))",
    "--color-border-orange": "light-dark(#ffc7a1, #df843f)",
    "--color-icon-orange": "light-dark(#94590A, #F1B45C)",
    "--color-text-orange": "light-dark(#94590A, #F1B45C)",
    "--color-background-yellow": "light-dark(#FCF0D4, rgba(233, 185, 73, 0.15))",
    "--color-border-yellow": "light-dark(#e3c36c, #c29900)",
    "--color-icon-yellow": "light-dark(#8A5A00, #E9B949)",
    "--color-text-yellow": "light-dark(#8A5A00, #E9B949)",
    "--color-background-green": "light-dark(#E2F2E5, rgba(108, 195, 130, 0.15))",
    "--color-border-green": "light-dark(#aad4a9, #6ab26b)",
    "--color-icon-green": "light-dark(#1E7A32, #6CC382)",
    "--color-text-green": "light-dark(#1E7A32, #6CC382)",
    "--color-background-teal": "light-dark(#DCF2EF, rgba(82, 209, 198, 0.14))",
    "--color-border-teal": "light-dark(#90d7c8, #4fb1a0)",
    "--color-icon-teal": "light-dark(#0B6E69, #52D1C6)",
    "--color-text-teal": "light-dark(#0B6E69, #52D1C6)",
    "--color-background-cyan": "light-dark(#9ae2f4, #274046)",
    "--color-border-cyan": "light-dark(#85d5e9, #49adc4)",
    "--color-icon-cyan": "light-dark(#004351, #71c7dd)",
    "--color-text-cyan": "light-dark(#004351, #85d5e9)",
    "--color-background-blue": "light-dark(#E6EEFA, rgba(77, 148, 242, 0.16))",
    "--color-border-blue": "light-dark(#a1caff, #5aa0f8)",
    "--color-icon-blue": "light-dark(#1A6FD2, #4D94F2)",
    "--color-text-blue": "light-dark(#1557A8, #8DBAF7)",
    "--color-background-purple": "light-dark(#EEE7FA, rgba(185, 154, 245, 0.16))",
    "--color-border-purple": "light-dark(#f3bfff, #d885eb)",
    "--color-icon-purple": "light-dark(#6D46B8, #B99AF5)",
    "--color-text-purple": "light-dark(#6D46B8, #B99AF5)",
    "--color-background-pink": "light-dark(#FBE4EA, rgba(244, 149, 182, 0.14))",
    "--color-border-pink": "light-dark(#ffc0d7, #fc78b1)",
    "--color-icon-pink": "light-dark(#B03A5B, #F495B6)",
    "--color-text-pink": "light-dark(#B03A5B, #F495B6)",
    "--color-background-gray": "light-dark(#e2e2e2, #303030)",
    "--color-border-gray": "light-dark(#d4d4d4, #262626)",
    "--color-icon-gray": "light-dark(#474747, #9e9e9e)",
    "--color-text-gray": "light-dark(#1b1b1b, #d4d4d4)",
    "--radius-none": "0px",
    "--radius-inner": "0.375rem",
    "--radius-element": "0.625rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1.125rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 1px 2px light-dark(rgba(0, 0, 0, 0.04), rgba(0, 0, 0, 0.3)), 0 3px 8px light-dark(rgba(0, 0, 0, 0.06), rgba(0, 0, 0, 0.35)), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.05))",
    "--shadow-med": "0 2px 4px light-dark(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.35)), 0 8px 20px light-dark(rgba(0, 0, 0, 0.08), rgba(0, 0, 0, 0.45)), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.07))",
    "--shadow-high": "0 4px 8px light-dark(rgba(0, 0, 0, 0.08), rgba(0, 0, 0, 0.45)), 0 24px 56px light-dark(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.6)), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.09))",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #0074e24D",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #0074e280",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #2f7d334D",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #f8d36a4D",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #de47454D",
    "--color-background-inverted": "light-dark(#0F1217, #F1F3F6)",
    "--color-track": "light-dark(#DDE1E7, #2C323B)",
    "--radius-chat": "1.25rem"
  },
  localTokens: {
    "--astryx-theme-neutral-color-status-fill-accent": "light-dark(#1A6FD2, #4D94F2)",
    "--astryx-theme-neutral-color-status-fill-success": "light-dark(#1E7A32, #6CC382)",
    "--astryx-theme-neutral-color-status-fill-warning": "light-dark(#8A5A00, #E9B949)",
    "--astryx-theme-neutral-color-status-fill-error": "light-dark(#B42330, #FF8177)",
    "--astryx-theme-neutral-color-status-muted-accent": "light-dark(#E6EEFA, rgba(77, 148, 242, 0.16))",
    "--astryx-theme-neutral-color-on-tint-neutral": "light-dark(#fafafa4D, #0a0a0a4D)",
    "--astryx-theme-neutral-color-on-tint-overlay-hover": "light-dark(#fafafa1A, #0a0a0a1A)",
    "--astryx-theme-neutral-color-on-tint-overlay-pressed": "light-dark(#fafafa33, #0a0a0a33)",
    "--astryx-theme-neutral-color-destructive-overlay-hover": "light-dark(#ff7f770D, #ee736c0D)",
    "--astryx-theme-neutral-color-destructive-overlay-pressed": "light-dark(#ff7f771A, #ee736c1A)",
    "--eneo-color-background-sunken": "light-dark(#F8F9FB, #0D1014)",
    "--eneo-color-text-tertiary": "light-dark(#646A77, #939BA8)",
    "--eneo-color-border-control": "light-dark(#7E8593, #747C8B)"
  },
  __localTokenOwners: {
    "--astryx-theme-neutral-color-status-fill-accent": "neutral",
    "--astryx-theme-neutral-color-status-fill-success": "neutral",
    "--astryx-theme-neutral-color-status-fill-warning": "neutral",
    "--astryx-theme-neutral-color-status-fill-error": "neutral",
    "--astryx-theme-neutral-color-status-muted-accent": "neutral",
    "--astryx-theme-neutral-color-on-tint-neutral": "neutral",
    "--astryx-theme-neutral-color-on-tint-overlay-hover": "neutral",
    "--astryx-theme-neutral-color-on-tint-overlay-pressed": "neutral",
    "--astryx-theme-neutral-color-destructive-overlay-hover": "neutral",
    "--astryx-theme-neutral-color-destructive-overlay-pressed": "neutral",
    "--eneo-color-background-sunken": "eneo",
    "--eneo-color-text-tertiary": "eneo",
    "--eneo-color-border-control": "eneo"
  },
  __localTokenLineage: ["neutral","eneo"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)",
        "--color-overlay-hover": "var(--astryx-theme-neutral-color-destructive-overlay-hover)",
        "--color-overlay-pressed": "var(--astryx-theme-neutral-color-destructive-overlay-pressed)"
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-accent)",
        "color": "var(--color-on-accent)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)",
        "color": "var(--color-on-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-warning)",
        "color": "var(--color-on-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)",
        "color": "var(--color-on-error)"
      },
      "variant:red": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      },
      "variant:orange": {
        "backgroundColor": "var(--color-background-orange)",
        "color": "var(--color-text-orange)"
      },
      "variant:yellow": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:green": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:teal": {
        "backgroundColor": "var(--color-background-teal)",
        "color": "var(--color-text-teal)"
      },
      "variant:cyan": {
        "backgroundColor": "var(--color-background-cyan)",
        "color": "var(--color-text-cyan)"
      },
      "variant:blue": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:purple": {
        "backgroundColor": "var(--color-background-purple)",
        "color": "var(--color-text-purple)"
      },
      "variant:pink": {
        "backgroundColor": "var(--color-background-pink)",
        "color": "var(--color-text-pink)"
      },
      "variant:gray": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      }
    },
    "status-dot": {
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:warning": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)"
      },
      "variant:accent": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-accent)"
      }
    },
    "avatar-status-dot": {
      "variant:success": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:error": {
        "backgroundColor": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "segmented-control": {
      "base": {
        "padding": "var(--spacing-1)"
      }
    },
    "segmented-control-item": {
      "size:sm": {
        "height": "calc(var(--size-element-sm) - 8px)"
      },
      "size:md": {
        "height": "calc(var(--size-element-md) - 8px)"
      },
      "size:lg": {
        "height": "calc(var(--size-element-lg) - 8px)"
      },
      "selected": {
        "boxShadow": "none"
      }
    },
    "banner": {
      "base": {
        "--color-neutral": "var(--astryx-theme-neutral-color-on-tint-neutral)",
        "--color-overlay-hover": "var(--astryx-theme-neutral-color-on-tint-overlay-hover)",
        "--color-overlay-pressed": "var(--astryx-theme-neutral-color-on-tint-overlay-pressed)"
      },
      "status:info": {
        "--color-accent-muted": "var(--astryx-theme-neutral-color-status-muted-accent)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      }
    },
    "step-indicator": {
      "status:accent": {
        "--color-accent": "var(--astryx-theme-neutral-color-status-fill-accent)"
      },
      "status:success": {
        "--color-success": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "status:warning": {
        "--color-warning": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "status:error": {
        "--color-error": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--eneo-color-border-control)"
      }
    },
    "progress-bar": {
      "base": {
        "--color-background-muted": "var(--color-border-emphasized)"
      },
      "variant:accent": {
        "--color-accent": "var(--astryx-theme-neutral-color-status-fill-accent)"
      },
      "variant:success": {
        "--color-success": "var(--astryx-theme-neutral-color-status-fill-success)"
      },
      "variant:warning": {
        "--color-warning": "var(--astryx-theme-neutral-color-status-fill-warning)"
      },
      "variant:error": {
        "--color-error": "var(--astryx-theme-neutral-color-status-fill-error)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "text-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "text-area": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "number-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "date-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "date-range-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "date-time-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "time-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "selector": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "multi-selector": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "complex-selector": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "typeahead": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "file-input": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "input-group": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "checkbox-indicator": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "radio-indicator": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    },
    "chat-composer": {
      "base": {
        "--color-border-emphasized": "var(--eneo-color-border-control)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 14,
        "ratio": 1.2
      },
      "body": {
        "family": "Figtree",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif"
      },
      "heading": {
        "family": "Figtree",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
        "weights": {
          "3": "bold",
          "4": "bold"
        }
      },
      "code": {
        "family": "ui-monospace",
        "fallbacks": "\"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
      }
    },
    "motion": {
      "fast": 125,
      "medium": 300,
      "slow": 700,
      "ratio": 0.75
    }
  },
  icons: neutralIconRegistry,
};

export { neutralIconRegistry };
