/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/eneo-theme.ts
 * Command: astryx theme build src/theme/eneo-theme.ts
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./eneo.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const eneoTheme: DefinedTheme;
