# flake8: noqa

import eneo.database.tables.ai_models_table
import eneo.database.tables.allowed_origins_table
import eneo.database.tables.api_keys_table
import eneo.database.tables.audit_action_config_table
import eneo.database.tables.audit_category_config_table
import eneo.database.tables.audit_log_table
import eneo.database.tables.audit_retention_policy_table
import eneo.database.tables.app_table
import eneo.database.tables.app_template_table
import eneo.database.tables.assistant_table
import eneo.database.tables.assistant_template_table
import eneo.database.tables.collections_table
import eneo.database.tables.completion_model_migration_history_table
import eneo.database.tables.feature_flag_table
import eneo.database.tables.files_table
import eneo.database.tables.group_chats_table
import eneo.database.tables.info_blob_chunk_table
import eneo.database.tables.info_blobs_table
import eneo.database.tables.sharepoint_subscription_table
import eneo.database.tables.tenant_sharepoint_app_table
import eneo.database.tables.integration_table
import eneo.database.tables.job_table
import eneo.database.tables.logging_table
import eneo.database.tables.module_table
import eneo.database.tables.prompts_table
import eneo.database.tables.questions_table
import eneo.database.tables.roles_table
import eneo.database.tables.service_table
import eneo.database.tables.sessions_table
import eneo.database.tables.settings_table
import eneo.database.tables.sync_log_table
import eneo.database.tables.spaces_table
import eneo.database.tables.tenant_table
import eneo.database.tables.user_groups_table
import eneo.database.tables.users_table
import eneo.database.tables.web_search_results_table
import eneo.database.tables.websites_table
import eneo.database.tables.widget_table
import eneo.database.tables.workflow_tables
import eneo.database.tables.groups_spaces_table
import eneo.database.tables.icons_table
import eneo.database.tables.websites_spaces_table
