import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import jsxA11y from "eslint-plugin-jsx-a11y";
import eneo from "@eneo/eslint-plugin";

const generatedAndVendored = [
  "src/lib/api/schema.d.ts",
  "src/lib/i18n/**",
  "src/components/ai-elements/**",
  "src/components/ui/**",
  "src/app/global-error.tsx",
  "src/app/(app)/chat-mock/**",
  "src/**/*.test.{ts,tsx}"
];

// UI that never ships: tests and the dev-only chat mock (404 in production).
// Vendored primitives DO ship, so the accessibility rules cover them too.
const notShippedUi = ["src/**/*.test.tsx", "src/app/(app)/chat-mock/**"];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    plugins: {
      eneo
    }
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `bun run theme:build` from src/theme/eneo-theme.ts.
    "src/theme/eneo.js",
    "src/theme/eneo.d.ts",
    "src/theme/eneo.variants.d.ts"
  ]),
  {
    // Vendored AI Elements (shadcn-style editable source). Upstream patterns
    // occasionally trip strict rules; relax instead of forking every file.
    files: ["src/components/ai-elements/**"],
    rules: {
      "react-hooks/refs": "off",
      "react-hooks/static-components": "off",
      "@typescript-eslint/no-unused-vars": "off"
    }
  },
  {
    // Port the shared eneo color guardrail to web-next app source. Vendored
    // primitives are intentionally exempted above and should stay close to
    // their upstream implementations.
    files: ["src/**/*.{ts,tsx}"],
    ignores: generatedAndVendored,
    rules: {
      "eneo/no-raw-color": "error"
    }
  },
  {
    // Block hardcoded human-facing JSX text in app code; route copy through
    // next-intl messages instead. Accessible names and descriptions in
    // attributes (aria-label, title, alt, placeholder, label, tooltip, …)
    // belong to eneo/no-literal-accessible-name below, so each literal is
    // reported once; this rule checks the text between tags and the other
    // display props.
    files: ["src/**/*.tsx"],
    ignores: generatedAndVendored,
    rules: {
      "eneo/no-hardcoded-text": [
        "error",
        {
          attributes: ["hint", "submitLabel"],
          ignore: [
            "Eneo\\.ai",
            "^(web-next|· backend)$",
            "^https?://$",
            "^(CSV|JSON|JSONL|PDF|URL|HTTP|HTTPS|OIDC|MCP|API|ID)$",
            "^SharePoint$",
            "^s$",
            "^(Ctrl|Enter|Shift|Alt|Cmd|Tab|Esc)$"
          ]
        }
      ]
    }
  },
  {
    // Accessibility: WCAG 2.2 AA, see ACCESSIBILITY.md. eslint-plugin-jsx-a11y's
    // strict set plus two rules it leaves out. eslint-config-next already
    // registers the `jsx-a11y` plugin (same package, pinned in package.json);
    // registering it again is a "Cannot redefine plugin" error, so only the
    // rules are taken from the plugin's config.
    //
    // Existing violations are baselined in eslint-suppressions.json and new ones
    // fail `bun run lint`. Fix, don't suppress; after fixing a baselined
    // violation run `bunx eslint --prune-suppressions` so the baseline shrinks.
    files: ["src/**/*.tsx"],
    ignores: notShippedUi,
    settings: {
      "jsx-a11y": {
        // Astryx `as="…"` renders that element; next/image and next/link are
        // checked like <img> and <a>.
        polymorphicPropName: "as",
        components: { Image: "img", Link: "a" }
      }
    },
    rules: {
      ...jsxA11y.flatConfigs.strict.rules,
      // Added to strict: focusable content inside aria-hidden (4.1.2) and
      // invalid lang values (3.1.1, 3.1.2).
      "jsx-a11y/no-aria-hidden-on-focusable": "error",
      "jsx-a11y/lang": "error",
      // Configured: text up to three levels deep counts as a wrapping label's
      // text (label + description spans), and the shadcn form primitives count
      // as controls.
      "jsx-a11y/label-has-associated-control": [
        "error",
        {
          depth: 3,
          labelComponents: ["Label"],
          controlComponents: [
            "Input",
            "Textarea",
            "Checkbox",
            "Switch",
            "RadioGroupItem",
            "SelectTrigger",
            "Slider"
          ]
        }
      ],
      // Relaxed from strict: a scrollable region must be focusable to scroll by
      // keyboard (2.1.1), so tabIndex={0} is allowed on role="region" (with an
      // accessible name) and on role="tabpanel" (WAI-ARIA tabs pattern).
      "jsx-a11y/no-noninteractive-tabindex": ["error", { roles: ["tabpanel", "region"], tags: [] }],
      // Accessible names and descriptions come from next-intl, never literals.
      "eneo/no-literal-accessible-name": "error"
    }
  },
  {
    // Toasts (2.2.1): errors and warnings stay until the user closes them.
    // src/lib/toast.ts owns that policy, so it and the Toaster are the only
    // shipped code that talks to sonner.
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/lib/toast.ts",
      "src/components/ui/sonner.tsx",
      "src/**/*.test.{ts,tsx}",
      "src/test/**"
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "sonner",
              message:
                "Use `toast` from @/lib/toast: it keeps errors and warnings up until they are closed."
            }
          ]
        }
      ]
    }
  },
  {
    // Visible focus (2.4.7, 1.4.11): no translucent focus rings (`ring-ring/50`
    // is about 2:1) and no `outline-none` without a focus-visible replacement
    // in the same class list. Class strings live in .ts files too.
    files: ["src/**/*.{ts,tsx}"],
    ignores: [...notShippedUi, "src/**/*.test.ts"],
    rules: {
      "eneo/no-weak-focus-indicator": "error"
    }
  },
  {
    // Astryx parts we wrap to work around their gaps (AGENTS.md → Reuse
    // before you build). A separate rule from no-restricted-imports above, so
    // neither block replaces the other's options.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/components/astryx/**"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@astryxdesign/core/Switch",
              message:
                'Use `Switch` from "@/components/astryx/switch": Astryx\'s busy state announces an English "Loading".'
            },
            {
              name: "@astryxdesign/core/Table",
              importNames: ["Table"],
              message:
                'Use `Table` from "@/components/astryx/table": it must be named, and names its scroll region.'
            }
          ]
        }
      ]
    }
  },
  {
    // Deprecated APIs (TanStack Query methods, React types, DOM properties)
    // are replaced while their successors exist, not when a major upgrade
    // removes them. The rule needs type information, so this block turns on
    // typed linting for app source.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/api/schema.d.ts"],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname }
    },
    rules: {
      "@typescript-eslint/no-deprecated": "error"
    }
  }
]);

export default eslintConfig;
