import hashlib
import json
import secrets
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional
from urllib.parse import urlencode
from uuid import UUID

import redis.asyncio as aioredis
from pydantic import BaseModel, ConfigDict, Field, field_validator

from eneo.audit.application.audit_service import AuditService
from eneo.audit.domain.action_types import ActionType
from eneo.audit.domain.actor_types import ActorType
from eneo.audit.domain.entity_types import EntityType
from eneo.authentication.api_key_v2_repo import ApiKeysV2Repository
from eneo.authentication.auth_models import (
    PERMISSION_LEVEL_ORDER,
    ApiKeyOwnership,
    ApiKeyPermission,
    ApiKeyType,
    ApiKeyV2InDB,
)
from eneo.authentication.auth_service import AuthService
from eneo.main.config import get_settings, validate_redirect_uri
from eneo.main.exceptions import (
    AuthenticationException,
    BadRequestException,
    NotFoundException,
    UnauthorizedException,
)
from eneo.modules.module import ModuleInDB
from eneo.modules.module_repo import ModuleRepository
from eneo.users.user import UserInDB
from eneo.users.user_repo import UsersRepository
from eneo.users.user_service import UserService

_TICKET_KEY_PREFIX = "module_auth_ticket:"
MODULE_AUDIENCE_PREFIX = "eneo-module:"
# Unix timestamp of the original ticket exchange, carried unchanged through
# every refresh so the session ceiling cannot slide. Tokens minted before the
# claim existed fall back to ``iat``, which equals the handoff time for any
# never-refreshed token.
MODULE_HANDOFF_AT_CLAIM = "handoff_at"
# Immutable identity claims minted at ticket exchange and preserved across
# refresh. Resource authentication resolves the principal by these - never by
# email: the active-email unique index excludes soft-deleted rows, so an email
# can move to a replacement account while an older module token is still valid.
MODULE_USER_ID_CLAIM = "user_id"
MODULE_TENANT_ID_CLAIM = "tenant_id"


class ModuleTicketRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    module_key: str = Field(
        min_length=1,
        description=(
            "Stable, case-sensitive public module key (the module's unique name), "
            "not its database UUID."
        ),
    )
    redirect_uri: str
    state: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=512,
        description=(
            "Opaque login-CSRF correlation value generated by the module "
            "before it redirects to Eneo. Echoed unmodified as `state` on "
            "`redirect_target`; the module must verify it against the browser "
            "session that initiated the login and accept each value once."
        ),
    )

    @field_validator("redirect_uri")
    @classmethod
    def normalize_redirect_uri(cls, value: str) -> str:
        redirect_uri = validate_redirect_uri(value)
        if redirect_uri is None:
            raise ValueError("redirect_uri is required")
        return redirect_uri


class ModuleTicketResponse(BaseModel):
    """The raw ticket travels only inside ``redirect_target`` - a single
    carrier keeps the secret surface minimal and leaves no field to build
    side-flows on."""

    redirect_target: str
    expires_in: int


class ModuleTokenRequest(BaseModel):
    ticket: str


class ModuleTokenUser(BaseModel):
    id: UUID
    email: str
    username: Optional[str] = None


class ModuleTokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int
    session_expires_at: datetime = Field(
        description=(
            "Absolute UTC ceiling of this module session, fixed at the "
            "original ticket exchange. Refresh can renew the token until this "
            "instant but never past it; afterwards a new login handoff is "
            "required."
        ),
    )
    module_key: str
    tenant_id: UUID
    user: ModuleTokenUser


class ModuleResourceSessionResponse(BaseModel):
    """Public identity returned after both module credentials pass."""

    module_key: str
    tenant_id: UUID
    user: ModuleTokenUser


@dataclass(frozen=True, slots=True)
class ModuleRequestPrincipal:
    """Live authorization result for one module resource request.

    ``access_token`` is the already-validated module user token that proved
    this request; the refresh flow re-reads its verified claims to carry the
    session ceiling forward.
    """

    module: ModuleInDB
    user: UserInDB
    api_key: ApiKeyV2InDB
    access_token: str


def module_audience(module_key: str) -> str:
    return f"{MODULE_AUDIENCE_PREFIX}{module_key}"


def _ticket_redis_key(ticket: str) -> str:
    # Store only a digest so a Redis snapshot cannot be replayed as tickets.
    return _TICKET_KEY_PREFIX + hashlib.sha256(ticket.encode()).hexdigest()


class ModuleAuthBroker:
    """SSO handoff between an Eneo session and a module BFF.

    A logged-in user gets a one-time, short-lived ticket bound to one module;
    the module exchanges it server-side - authenticated with the sk_ key
    registered for that module - for a short-lived, module-scoped user token.
    The module session itself never authorizes anything: module-facing
    endpoints re-validate the token on every call.
    """

    def __init__(
        self,
        redis_client: aioredis.Redis,
        module_repo: ModuleRepository,
        api_key_repo: ApiKeysV2Repository,
        user_repo: UsersRepository,
        user_service: UserService,
        auth_service: AuthService,
        audit_service: AuditService,
    ) -> None:
        self.redis_client = redis_client
        self.module_repo = module_repo
        self.api_key_repo = api_key_repo
        self.user_repo = user_repo
        self.user_service = user_service
        self.auth_service = auth_service
        self.audit_service = audit_service

    @staticmethod
    def _service_key_registration_error(api_key: ApiKeyV2InDB) -> str | None:
        """Durable reason this key can never be a module exchange key, or None.

        scope_type is deliberately not restricted here: module keys follow
        least privilege (typically space-scoped, see docs/deployment/MODULES.md),
        and the right to exchange tickets comes from the exact service_key_id
        binding on the tenant-module row - not from the key's resource scope.
        """
        if api_key.ownership != ApiKeyOwnership.SERVICE:
            return "the API key must be service-owned"
        if api_key.key_type != ApiKeyType.SK:
            return "the API key must use the sk_ key type"

        granted = PERMISSION_LEVEL_ORDER.get(api_key.permission.value, 0)
        required = PERMISSION_LEVEL_ORDER[ApiKeyPermission.WRITE.value]
        if granted < required:
            return "the API key must have write or admin permission"
        return None

    async def validate_client_config_service_key(
        self, *, tenant_id: UUID, service_key_id: UUID
    ) -> None:
        """Validate the durable invariants for a module exchange key.

        Runtime state such as suspension, expiry, IP allowlists, and rate limits
        remains owned by normal API-key authentication. This registration check
        rejects configurations that can never authenticate successfully.
        """
        api_key = await self.api_key_repo.get(
            key_id=service_key_id, tenant_id=tenant_id
        )
        if api_key is None:
            raise BadRequestException(
                "service_key_id must reference an API key in the target tenant."
            )

        registration_error = self._service_key_registration_error(api_key)
        if registration_error is not None:
            raise BadRequestException(
                f"Invalid module service key: {registration_error}."
            )

    async def issue_ticket(
        self,
        user: UserInDB,
        module_key: str,
        redirect_uri: str,
        state: Optional[str] = None,
    ) -> ModuleTicketResponse:
        settings = get_settings()
        try:
            normalized_redirect_uri = validate_redirect_uri(redirect_uri)
        except ValueError as exc:
            raise BadRequestException(str(exc)) from exc
        if normalized_redirect_uri is None:
            raise BadRequestException("redirect_uri is invalid.")
        redirect_uri = normalized_redirect_uri

        module = await self.module_repo.get_module_by_key(module_key)
        if module is None:
            raise NotFoundException("Module not found.")

        config = await self.module_repo.get_module_client_config(
            tenant_id=user.tenant_id, module_id=module.id
        )
        if config is None:
            raise UnauthorizedException("Module is not enabled for this tenant.")

        if not config.redirect_uris or config.service_key_id is None:
            raise BadRequestException(
                "Module is not configured for login handoff "
                "(missing redirect_uris or service key registration)."
            )

        if redirect_uri not in config.redirect_uris:
            raise BadRequestException("redirect_uri is not registered for this module.")

        ticket = secrets.token_urlsafe(32)
        ttl = settings.module_auth_ticket_ttl_seconds
        payload = json.dumps(
            {
                "user_id": str(user.id),
                "tenant_id": str(user.tenant_id),
                "module_id": str(module.id),
            }
        )
        await self.redis_client.setex(_ticket_redis_key(ticket), ttl, payload)

        await self.audit_service.log_async(
            tenant_id=user.tenant_id,
            actor_id=user.id,
            actor_type=ActorType.USER,
            action=ActionType.MODULE_AUTH_TICKET_ISSUED,
            entity_type=EntityType.MODULE,
            entity_id=module.id,
            description=f"Issued module login ticket for '{module.name}'",
            metadata={"module": {"id": str(module.id), "name": module.name}},
        )

        # `state` is echoed, never stored: the CSRF binding it provides lives in
        # the module's browser session, exactly like OAuth `state`. The server
        # cannot verify it - the module must compare and consume it on callback.
        query_params = {"ticket": ticket}
        if state is not None:
            query_params["state"] = state
        separator = "&" if "?" in redirect_uri else "?"
        redirect_target = f"{redirect_uri}{separator}{urlencode(query_params)}"
        return ModuleTicketResponse(redirect_target=redirect_target, expires_in=ttl)

    async def exchange_ticket(
        self, api_key: ApiKeyV2InDB, ticket: str
    ) -> ModuleTokenResponse:
        registration_error = self._service_key_registration_error(api_key)
        if registration_error is not None:
            raise UnauthorizedException(
                "Module ticket exchange requires a service-owned sk_ key "
                "with write or admin permission."
            )

        ticket_key = _ticket_redis_key(ticket)
        raw = await self.redis_client.get(ticket_key)
        if raw is None:
            raise AuthenticationException("Invalid or expired module ticket.")

        data = json.loads(raw)
        module = await self.module_repo.get_module(UUID(data["module_id"]))
        tenant_id = UUID(data["tenant_id"])
        module_id = UUID(data["module_id"])
        config = await self.module_repo.get_module_client_config(
            tenant_id=tenant_id, module_id=module_id
        )

        # Binding: only the key registered for this module may exchange its
        # tickets. A rotated successor stays valid (it points back at the
        # registered key via rotated_from_key_id) until the operator updates
        # the registration.
        allowed_ids = {api_key.id, api_key.rotated_from_key_id} - {None}
        if (
            module is None
            or config is None
            or config.service_key_id is None
            or config.service_key_id not in allowed_ids
        ):
            raise UnauthorizedException("API key is not registered for this module.")

        if api_key.tenant_id != tenant_id:
            raise UnauthorizedException("API key belongs to a different tenant.")

        user = await self.user_repo.get_user_by_id_and_tenant_id(
            UUID(data["user_id"]), tenant_id=tenant_id
        )
        if user is None or not user.is_active:
            raise AuthenticationException("User is not active.")
        await self.user_service.validate_active_identity(
            user, correlation_id="module-ticket-exchange"
        )

        consumed = await self.redis_client.getdel(ticket_key)
        if consumed is None or consumed != raw:
            raise AuthenticationException("Invalid or expired module ticket.")

        handoff_at = int(time.time())
        expires_in_seconds, session_expires_at = self._token_window(handoff_at)
        access_token = self.auth_service.create_access_token_for_user(
            user,
            audience=module_audience(module.name),
            expires_in=expires_in_seconds / 60,
            extra_claims={
                MODULE_HANDOFF_AT_CLAIM: handoff_at,
                MODULE_USER_ID_CLAIM: str(user.id),
                MODULE_TENANT_ID_CLAIM: str(user.tenant_id),
            },
        )

        await self.audit_service.log_async(
            tenant_id=tenant_id,
            actor_id=user.id,
            actor_type=ActorType.USER,
            action=ActionType.MODULE_AUTH_TOKEN_EXCHANGED,
            entity_type=EntityType.MODULE,
            entity_id=module.id,
            description=f"Module '{module.name}' exchanged a login ticket",
            metadata={
                "module": {"id": str(module.id), "name": module.name},
                "api_key_id": str(api_key.id),
            },
        )

        return ModuleTokenResponse(
            access_token=access_token,
            expires_in=expires_in_seconds,
            session_expires_at=session_expires_at,
            module_key=module.name,
            tenant_id=tenant_id,
            user=ModuleTokenUser(id=user.id, email=user.email, username=user.username),
        )

    @staticmethod
    def _token_window(handoff_at: int) -> tuple[int, datetime]:
        """Seconds the next token may live, plus the fixed session ceiling.

        The ceiling is anchored at ``handoff_at``, so a token minted late in
        the session is clipped and no token is ever valid past the ceiling.
        Raises when the ceiling has passed - the caller turns that into a
        re-handoff signal.
        """
        settings = get_settings()
        ceiling = handoff_at + settings.module_auth_max_session_hours * 3600
        remaining = ceiling - int(time.time())
        if remaining <= 0:
            raise AuthenticationException(
                "Module session has reached its maximum length; "
                "a new login handoff is required."
            )
        expires_in_seconds = min(
            settings.module_auth_token_expiry_minutes * 60, remaining
        )
        session_expires_at = datetime.fromtimestamp(ceiling, tz=timezone.utc)
        return expires_in_seconds, session_expires_at

    async def refresh_token(
        self, *, principal: ModuleRequestPrincipal
    ) -> ModuleTokenResponse:
        """Renew a still-valid module user token inside the session ceiling.

        The caller must have run the full dual-credential resource
        authentication for this request; refresh therefore re-validates the
        same live state as any module resource call. An expired token cannot
        be refreshed - renewal after expiry is always a new login handoff, so
        access re-anchors in the central session gate.
        """
        settings = get_settings()
        module = principal.module
        user = principal.user

        claims = self.auth_service.get_verified_claims(
            principal.access_token,
            key=str(settings.jwt_secret),
            aud=module_audience(module.name),
        )
        try:
            handoff_at = int(float(claims.get(MODULE_HANDOFF_AT_CLAIM, claims["iat"])))
        except (KeyError, TypeError, ValueError) as exc:
            raise AuthenticationException(
                "Could not validate token credentials."
            ) from exc

        expires_in_seconds, session_expires_at = self._token_window(handoff_at)
        access_token = self.auth_service.create_access_token_for_user(
            user,
            audience=module_audience(module.name),
            expires_in=expires_in_seconds / 60,
            extra_claims={
                MODULE_HANDOFF_AT_CLAIM: handoff_at,
                MODULE_USER_ID_CLAIM: str(user.id),
                MODULE_TENANT_ID_CLAIM: str(user.tenant_id),
            },
        )

        await self.audit_service.log_async(
            tenant_id=user.tenant_id,
            actor_id=user.id,
            actor_type=ActorType.USER,
            action=ActionType.MODULE_AUTH_TOKEN_REFRESHED,
            entity_type=EntityType.MODULE,
            entity_id=module.id,
            description=f"Module '{module.name}' refreshed a module user token",
            metadata={
                "module": {"id": str(module.id), "name": module.name},
                "api_key_id": str(principal.api_key.id),
                "handoff_at": handoff_at,
                "session_expires_at": session_expires_at.isoformat(),
            },
        )

        return ModuleTokenResponse(
            access_token=access_token,
            expires_in=expires_in_seconds,
            session_expires_at=session_expires_at,
            module_key=module.name,
            tenant_id=user.tenant_id,
            user=ModuleTokenUser(id=user.id, email=user.email, username=user.username),
        )

    def validate_module_user_token(
        self, token: str, module: ModuleInDB
    ) -> dict[str, Any]:
        """Validate a module user token for the given module.

        Module-facing endpoints call this on EVERY request (alongside the sk_
        key check) - the module session alone must never authorize anything.
        Returns the verified claims, including the identity claims minted at
        exchange. Raises AuthenticationException on any mismatch (signature,
        expiry, or audience minted for a different module).
        """
        settings = get_settings()
        key = str(settings.jwt_secret)
        aud = module_audience(module.name)
        self.auth_service.get_jwt_payload(token, key=key, aud=aud)
        return self.auth_service.get_verified_claims(token, key=key, aud=aud)

    async def authenticate_resource_request(
        self,
        *,
        module_key: str,
        access_token: str,
        api_key: ApiKeyV2InDB,
    ) -> ModuleRequestPrincipal:
        """Validate both credentials and all live module authorization state.

        The raw service key must already have passed the normal API-key
        resolver, including revocation, expiry, allowlist and rate-limit
        checks. This method adds the module-specific binding and independently
        validates the short-lived user token against the expected module
        audience. The principal is resolved by the token's immutable user-id
        and tenant-id claims, and user/tenant state is read on every request
        so disabling either takes effect immediately.
        """
        registration_error = self._service_key_registration_error(api_key)
        if registration_error is not None:
            raise UnauthorizedException(
                "Module resources require a service-owned sk_ key with write "
                "or admin permission."
            )

        module = await self.module_repo.get_module_by_key(module_key)
        if module is None:
            raise NotFoundException("Module not found.")

        config = await self.module_repo.get_module_client_config(
            tenant_id=api_key.tenant_id,
            module_id=module.id,
        )
        allowed_ids = {api_key.id, api_key.rotated_from_key_id} - {None}
        if (
            config is None
            or config.service_key_id is None
            or config.service_key_id not in allowed_ids
        ):
            raise UnauthorizedException("API key is not registered for this module.")

        claims = self.validate_module_user_token(access_token, module)
        try:
            token_user_id = UUID(str(claims[MODULE_USER_ID_CLAIM]))
            token_tenant_id = UUID(str(claims[MODULE_TENANT_ID_CLAIM]))
        except (KeyError, ValueError) as exc:
            raise AuthenticationException(
                "Could not validate token credentials."
            ) from exc

        if token_tenant_id != api_key.tenant_id:
            raise AuthenticationException("Module user is not active in this tenant.")

        user = await self.user_repo.get_user_by_id_and_tenant_id(
            token_user_id, tenant_id=token_tenant_id
        )
        if user is None or not user.is_active:
            raise AuthenticationException("Module user is not active in this tenant.")

        await self.user_service.validate_active_identity(
            user, correlation_id="module-resource-auth"
        )
        return ModuleRequestPrincipal(
            module=module, user=user, api_key=api_key, access_token=access_token
        )
