from eneo.flows.flow_api_error_code import FlowApiErrorCode

FLOW_REVIEW_EXPIRY_MIN_SECONDS = 60
FLOW_REVIEW_EXPIRY_MAX_SECONDS = 90 * 24 * 60 * 60
FLOW_REVIEW_EXPIRY_DEFAULT_SECONDS = 14 * 24 * 60 * 60
FLOW_REVIEW_EXPIRY_RECONCILE_INTERVAL_SECONDS = 60
FLOW_REVIEW_EXPIRY_UNHEALTHY_AFTER_INTERVALS = 2
FLOW_REVIEW_EXPIRY_UNHEALTHY_AFTER_SECONDS = (
    FLOW_REVIEW_EXPIRY_RECONCILE_INTERVAL_SECONDS
    * FLOW_REVIEW_EXPIRY_UNHEALTHY_AFTER_INTERVALS
)
FLOW_REVIEW_EXPIRED = FlowApiErrorCode.REVIEW_EXPIRED.value
FLOW_REVIEW_EXPIRED_TERMINAL_MESSAGE = (
    f"{FLOW_REVIEW_EXPIRED}: Review checkpoint expired before it was completed."
)
