import { createEneo } from "./src/eneo";
export { createEneo } from "./src/eneo";
import { createEneoSocket } from "./src/socket/socket";
export { createEneoSocket } from "./src/socket/socket";
export { createClient, EneoError } from "./src/client/client";
export { JSONRequestBody } from "./src/types/fetch";
export * from "./src/types/resources";
export * from "./src/socket/types";
export type Eneo = ReturnType<typeof createEneo>;
export type EneoSocket = ReturnType<typeof createEneoSocket>;
