<!--
 The primary purpose of this component is to render the responses generated by the LLM inside eneo.
 In order to achieve this, we use the marked lexer and generate a token list from the LLM's response.
 The tokens are then mapped to components and rendered.
 Performance: the whole source is re-lexed every time it changes, which during streaming is every
 buffered flush. That is cheap; what is not cheap is rebuilding the component tree. The lexer returns
 new token objects on every run, so the each blocks in this tree key on position, not on the token:
 existing components receive the new token as a prop and Svelte only patches the text that changed.
 Keying on the token object would tear down and recreate every rendered block on every flush.
 -->
<script lang="ts">
  import { eneoMarkdownLexer } from "./index.js";
  import RenderToken from "./renderers/RenderToken.svelte";
  import { initReferenceContext } from "./ReferenceContext.js";
  import type { CustomRenderers } from "./CustomComponents.js";
  import type { InfoBlob } from "@eneo/eneo-js";
  import type { ClassValue } from "svelte/elements";

  type Props = {
    source: string;
    references?: InfoBlob[];
    customRenderers?: CustomRenderers;
    showTokenOutput?: boolean;
    class?: ClassValue;
  };

  let {
    source,
    customRenderers = {},
    showTokenOutput = false,
    references = [],
    class: cls
  }: Props = $props();

  const lexer = eneoMarkdownLexer();

  initReferenceContext({
    references: () => references,
    renderer: () => customRenderers.inref
  });

  const tokens = $derived(lexer.lex(source));
</script>

<div class={["prose text-lg break-words", cls]}>
  {#each tokens as token, i (i)}
    <RenderToken {token}></RenderToken>
  {/each}
</div>

{#if showTokenOutput}
  <pre>{JSON.stringify(tokens, undefined, 2)}</pre>
{/if}
