"""migrate_model_defaults_to_jsonb
Revision ID: 88aa5736d5e6
Revises: 14df4152f4b8
Create Date: 2025-09-01 11:34:32.525128
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = '88aa5736d5e6'
down_revision = '970ed4255047'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completion_models', sa.Column('default_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completion_models', 'default_settings')
    # ### end Alembic commands ###
