"""add normalized parameter fields to completion models

Revision ID: 14df4152f4b8
Revises: 970ed4255047
Create Date: 2025-09-01 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '14df4152f4b8'
down_revision = '970ed4255047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completion_models', sa.Column('default_temperature', sa.Float(), nullable=True))
    op.add_column('completion_models', sa.Column('default_top_p', sa.Float(), nullable=True))
    op.add_column('completion_models', sa.Column('default_reasoning_effort', sa.String(), nullable=True))
    op.add_column('completion_models', sa.Column('default_verbosity', sa.String(), nullable=True))
    op.add_column('completion_models', sa.Column('default_max_completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completion_models', 'default_max_completion_tokens')
    op.drop_column('completion_models', 'default_verbosity')
    op.drop_column('completion_models', 'default_reasoning_effort')
    op.drop_column('completion_models', 'default_top_p')
    op.drop_column('completion_models', 'default_temperature')
    # ### end Alembic commands ###