"""add_litellm_model_name_to_embedding_models
Revision ID: f6ae7dc6c04f
Revises: a1b2c3d4e5f6
Create Date: 2025-09-03 08:00:55.758159
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'f6ae7dc6c04f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_models', sa.Column('litellm_model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_models', 'litellm_model_name')
    # ### end Alembic commands ###
