"""Create the final core Flow schema.

Revision ID: 202608201000
Revises: 202608181000
Create Date: 2026-08-20 07:29:40.748558
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = "202608201000"
down_revision = "202608181000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tenant-safe Flow file relationships need a stable composite target.
    op.create_unique_constraint("uq_files_id_tenant_id", "files", ["id", "tenant_id"])
    op.create_table(
        "flows",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("data_retention_days", sa.Integer(), nullable=True),
        sa.Column("draft_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_retention_days IS NULL OR (data_retention_days >= 1 AND data_retention_days <= 2555)",
            name="ck_flows_data_retention_days_range",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "tenant_id", "space_id", name="uq_flows_id_tenant_id_space_id"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_flows_id_tenant_id"),
    )
    op.create_index(
        "ix_flows_space_deleted", "flows", ["space_id", "deleted_at"], unique=False
    )
    op.create_index(op.f("ix_flows_space_id"), "flows", ["space_id"], unique=False)
    op.create_index(op.f("ix_flows_tenant_id"), "flows", ["tenant_id"], unique=False)
    op.create_index(
        "uq_flows_space_id_name_active",
        "flows",
        ["space_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "flow_versions",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("definition_checksum", sa.String(), nullable=False),
        sa.Column(
            "definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_versions_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("flow_id", "version"),
        sa.UniqueConstraint("flow_id", "version", name="uq_flow_versions_flow_version"),
    )
    op.create_index(
        op.f("ix_flow_versions_tenant_id"), "flow_versions", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        "fk_flows_published_version",
        "flows",
        "flow_versions",
        ["id", "published_version"],
        ["flow_id", "version"],
        ondelete="NO ACTION",
        onupdate="NO ACTION",
    )
    op.create_table(
        "service_principals",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(), server_default="active", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((state = 'active' AND disabled_at IS NULL) OR (state = 'disabled' AND disabled_at IS NOT NULL))",
            name="ck_service_principals_disabled_at_matches_state",
        ),
        sa.CheckConstraint(
            "state IN ('active', 'disabled')", name="ck_service_principals_state"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name="fk_service_principals_created_by_user",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_service_principals_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_service_principals_tenant_id",
        "service_principals",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_package_imports",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("package_id", sa.String(length=128), nullable=False),
        sa.Column("package_version", sa.String(length=64), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "import_plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "selected_mappings_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "failure_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'draft_created' AND flow_id IS NOT NULL AND failure_json IS NULL) OR (status = 'failed' AND flow_id IS NULL AND failure_json IS NOT NULL)",
            name="ck_flow_package_imports_terminal_shape",
        ),
        sa.CheckConstraint(
            "content_checksum ~ '^[0-9a-f]{64}$'",
            name="ck_flow_package_imports_content_checksum",
        ),
        sa.CheckConstraint(
            "source IN ('file_upload')", name="ck_flow_package_imports_source"
        ),
        sa.CheckConstraint(
            "status IN ('draft_created','failed')",
            name="ck_flow_package_imports_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id", "space_id"],
            ["flows.id", "flows.tenant_id", "flows.space_id"],
            name="fk_flow_package_imports_flow_tenant_space",
            onupdate="NO ACTION",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flow_package_imports_flow_id"),
        "flow_package_imports",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_package_imports_space_checksum_created",
        "flow_package_imports",
        ["space_id", "content_checksum", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_package_imports_space_id"),
        "flow_package_imports",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_package_imports_tenant_id"),
        "flow_package_imports",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_package_imports_tenant_space_created",
        "flow_package_imports",
        ["tenant_id", "space_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "flow_resource_bindings",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("slot_kind", sa.String(length=32), nullable=False),
        sa.Column("slot", sa.String(length=96), nullable=False),
        sa.Column("slot_label", sa.String(length=160), nullable=False),
        sa.Column("local_resource_kind", sa.String(length=64), nullable=False),
        sa.Column("local_resource_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(slot_kind, local_resource_kind) IN (('model','completion_model'),('model','transcription_model'),('knowledge','collection'),('knowledge','integration_knowledge'),('knowledge','website'),('template_asset','template_asset'))",
            name="ck_flow_resource_bindings_slot_local_kind_pair",
        ),
        sa.CheckConstraint(
            "local_resource_kind IN ('completion_model','transcription_model','collection','website','integration_knowledge','template_asset')",
            name="ck_flow_resource_bindings_local_resource_kind",
        ),
        sa.CheckConstraint(
            "slot !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'",
            name="ck_flow_resource_bindings_slot_not_uuid",
        ),
        sa.CheckConstraint(
            "slot ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$'",
            name="ck_flow_resource_bindings_slot_format",
        ),
        sa.CheckConstraint(
            "slot_kind IN ('model','knowledge','template_asset')",
            name="ck_flow_resource_bindings_slot_kind",
        ),
        sa.CheckConstraint(
            "source IN ('package_import','manual_admin')",
            name="ck_flow_resource_bindings_source",
        ),
        sa.CheckConstraint(
            "length(btrim(slot_label)) > 0",
            name="ck_flow_resource_bindings_slot_label_not_empty",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_resource_bindings_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_id", "slot_kind", "slot", name="uq_flow_resource_bindings_flow_slot"
        ),
    )
    op.create_index(
        op.f("ix_flow_resource_bindings_flow_id"),
        "flow_resource_bindings",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_resource_bindings_local_target",
        "flow_resource_bindings",
        ["local_resource_kind", "local_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_resource_bindings_space_id"),
        "flow_resource_bindings",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_resource_bindings_tenant_flow",
        "flow_resource_bindings",
        ["tenant_id", "flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_resource_bindings_tenant_id"),
        "flow_resource_bindings",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "provider_token_usages",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_user_id", sa.UUID(), nullable=True),
        sa.Column("principal_service_id", sa.UUID(), nullable=True),
        sa.Column("completion_model_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name="ck_provider_token_usages_input_nonnegative",
        ),
        sa.CheckConstraint(
            "length(source_type) > 0",
            name="ck_provider_token_usages_source_type_nonempty",
        ),
        sa.CheckConstraint(
            "num_nonnulls(principal_user_id, principal_service_id) = 1",
            name="ck_provider_token_usages_principal_identity",
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name="ck_provider_token_usages_output_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["completion_model_id"], ["completion_models.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["principal_service_id"], ["service_principals.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["principal_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_type", "source_id", name="uq_provider_token_usages_source"
        ),
    )
    op.create_index(
        "ix_provider_token_usages_completion_model_id",
        "provider_token_usages",
        ["completion_model_id"],
        unique=False,
    )
    op.create_index(
        "ix_provider_token_usages_tenant_occurred",
        "provider_token_usages",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "flow_runs",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("flow_version", sa.Integer(), nullable=False),
        sa.Column(
            "principal_type",
            sa.String(length=32),
            server_default="user",
            nullable=False,
        ),
        sa.Column("principal_user_id", sa.UUID(), nullable=True),
        sa.Column("principal_service_id", sa.UUID(), nullable=True),
        sa.Column("created_by_api_key_id", sa.UUID(), nullable=True),
        sa.Column("runtime_service_permission", sa.String(length=32), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "trace_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "revision",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Monotonic lifecycle compare-and-swap token; its value on entry to queued identifies the dispatch epoch.",
        ),
        sa.Column(
            "status", sa.String(length=32), server_default="queued", nullable=False
        ),
        sa.Column("dispatch_pending_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "dispatch_attempt_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "dispatch_last_attempt_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "dispatch_last_error",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "dispatch_next_attempt_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatch_exhausted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "input_payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "output_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((principal_type = 'user' AND principal_user_id IS NOT NULL AND principal_service_id IS NULL AND runtime_service_permission IS NULL) OR (principal_type = 'service_key' AND principal_user_id IS NULL AND principal_service_id IS NOT NULL AND runtime_service_permission IN ('read','write','admin')))",
            name="ck_flow_runs_principal_identity",
        ),
        sa.CheckConstraint(
            "dispatch_last_error IS NULL OR jsonb_typeof(dispatch_last_error) = 'object'",
            name="ck_flow_runs_dispatch_last_error_object",
        ),
        sa.CheckConstraint(
            "principal_type IN ('user','service_key')",
            name="ck_flow_runs_principal_type",
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','awaiting_review','completed','failed','cancelled')",
            name="ck_flow_runs_status",
        ),
        sa.CheckConstraint(
            "dispatch_attempt_count >= 0",
            name="ck_flow_runs_dispatch_attempt_count_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_api_key_id"], ["api_keys_v2.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "flow_version"],
            ["flow_versions.flow_id", "flow_versions.version"],
            name="fk_flow_runs_flow_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_runs_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["principal_service_id"], ["service_principals.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["principal_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "flow_id", name="uq_flow_runs_id_flow_id"),
        sa.UniqueConstraint("id", "tenant_id", name="uq_flow_runs_id_tenant_id"),
    )
    op.create_index(
        op.f("ix_flow_runs_flow_id"), "flow_runs", ["flow_id"], unique=False
    )
    op.create_index(
        "ix_flow_runs_flow_id_status", "flow_runs", ["flow_id", "status"], unique=False
    )
    op.create_index("ix_flow_runs_job_id", "flow_runs", ["job_id"], unique=False)
    op.create_index(
        "ix_flow_runs_queued_dispatch_due",
        "flow_runs",
        ["tenant_id", "dispatch_next_attempt_at", "id"],
        unique=False,
        postgresql_where=sa.text(
            "status = 'queued' AND dispatch_next_attempt_at IS NOT NULL AND dispatch_exhausted_at IS NULL"
        ),
    )
    op.create_index(
        "ix_flow_runs_running_updated_at",
        "flow_runs",
        ["status", "updated_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "ix_flow_runs_service_principal_created_at",
        "flow_runs",
        ["tenant_id", "principal_service_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("principal_type = 'service_key'"),
    )
    op.create_index(op.f("ix_flow_runs_status"), "flow_runs", ["status"], unique=False)
    op.create_index(
        "ix_flow_runs_tenant_created_at",
        "flow_runs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_runs_tenant_id"), "flow_runs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_flow_runs_terminal_retention_anchor",
        "flow_runs",
        [sa.literal_column("coalesce(finished_at, created_at)"), "id"],
        unique=False,
        postgresql_include=("flow_id",),
        postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"),
    )
    op.create_index(
        op.f("ix_flow_runs_trace_id"), "flow_runs", ["trace_id"], unique=False
    )
    op.create_index(
        "uq_flow_runs_idempotency_service_key",
        "flow_runs",
        ["tenant_id", "flow_id", "principal_service_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text(
            "principal_type = 'service_key' AND idempotency_key IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_flow_runs_idempotency_user_key",
        "flow_runs",
        ["tenant_id", "flow_id", "principal_user_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text(
            "principal_type = 'user' AND idempotency_key IS NOT NULL"
        ),
    )
    op.create_table(
        "flow_runtime_uploaded_files",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "uploaded_for_step_id",
            sa.Uuid(),
            nullable=False,
            comment="Published runtime step id that accepted the upload; provenance metadata, not a draft flow_steps foreign key.",
        ),
        sa.Column("owner_type", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("owner_service_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(owner_type = 'user' AND owner_user_id IS NOT NULL AND owner_service_id IS NULL) OR (owner_type = 'service_key' AND owner_user_id IS NULL AND owner_service_id IS NOT NULL)",
            name="ck_flow_runtime_uploaded_files_owner_identity",
        ),
        sa.CheckConstraint(
            "owner_type IN ('user','service_key')",
            name="ck_flow_runtime_uploaded_files_owner_type",
        ),
        sa.ForeignKeyConstraint(
            ["file_id", "tenant_id"],
            ["files.id", "files.tenant_id"],
            name="fk_flow_runtime_uploaded_files_file_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_runtime_uploaded_files_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_service_id"], ["service_principals.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
        sa.UniqueConstraint(
            "file_id",
            "flow_id",
            "tenant_id",
            name="uq_flow_runtime_uploaded_files_file_flow_tenant",
        ),
    )
    op.create_index(
        op.f("ix_flow_runtime_uploaded_files_flow_id"),
        "flow_runtime_uploaded_files",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_runtime_uploaded_files_service_owner",
        "flow_runtime_uploaded_files",
        ["tenant_id", "flow_id", "owner_service_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("owner_type = 'service_key'"),
    )
    op.create_index(
        op.f("ix_flow_runtime_uploaded_files_tenant_id"),
        "flow_runtime_uploaded_files",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_runtime_uploaded_files_user_owner",
        "flow_runtime_uploaded_files",
        ["tenant_id", "flow_id", "owner_user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("owner_type = 'user'"),
    )
    op.create_table(
        "flow_template_assets",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("mimetype", sa.String(), nullable=True),
        sa.Column(
            "placeholders",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="ready", nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ready','needs_action','read_only','unavailable')",
            name="ck_flow_template_assets_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["file_id", "tenant_id"],
            ["files.id", "files.tenant_id"],
            name="fk_flow_template_assets_file_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_template_assets_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "tenant_id", name="uq_flow_template_assets_id_tenant_id"
        ),
    )
    op.create_index(
        op.f("ix_flow_template_assets_file_id"),
        "flow_template_assets",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_template_assets_flow_active",
        "flow_template_assets",
        ["flow_id", "updated_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_flow_template_assets_flow_id"),
        "flow_template_assets",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_template_assets_space_id"),
        "flow_template_assets",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_template_assets_tenant_id"),
        "flow_template_assets",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_run_step_input_files",
        sa.Column("flow_run_id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_no >= 1", name="ck_flow_run_step_input_files_attempt_no_positive"
        ),
        sa.ForeignKeyConstraint(
            ["file_id", "flow_id", "tenant_id"],
            [
                "flow_runtime_uploaded_files.file_id",
                "flow_runtime_uploaded_files.flow_id",
                "flow_runtime_uploaded_files.tenant_id",
            ],
            name="fk_flow_run_step_input_files_runtime_upload",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_run_step_input_files_run_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_run_step_input_files_run_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            "file_id",
            name="uq_flow_run_step_input_files_run_step_attempt_file",
        ),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            "ordinal",
            name="uq_flow_run_step_input_files_run_step_attempt_ordinal",
        ),
    )
    op.create_index(
        op.f("ix_flow_run_step_input_files_file_id"),
        "flow_run_step_input_files",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_input_files_flow_id"),
        "flow_run_step_input_files",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_input_files_flow_run_id"),
        "flow_run_step_input_files",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_input_files_flow_step",
        "flow_run_step_input_files",
        ["flow_id", "step_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_input_files_run_step_attempt",
        "flow_run_step_input_files",
        ["flow_run_id", "step_id", "attempt_no"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_input_files_tenant_file",
        "flow_run_step_input_files",
        ["tenant_id", "file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_input_files_tenant_id"),
        "flow_run_step_input_files",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_step_attempts",
        sa.Column("flow_run_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("dispatch_task_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("requested_model", sa.String(), nullable=True),
        sa.Column("response_model", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("finish_reason", sa.String(), nullable=True),
        sa.Column("provider_response_id", sa.String(), nullable=True),
        sa.Column("num_tokens_input", sa.Integer(), nullable=True),
        sa.Column("num_tokens_output", sa.Integer(), nullable=True),
        sa.Column(
            "provenance_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "input_payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "output_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("flow_step_execution_hash", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('started','failed','completed','cancelled')",
            name="ck_flow_step_attempts_status",
        ),
        sa.CheckConstraint(
            "attempt_no >= 1", name="ck_flow_step_attempts_attempt_no_positive"
        ),
        sa.CheckConstraint(
            "step_order >= 1", name="ck_flow_step_attempts_step_order_positive"
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_step_attempts_run_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_step_attempts_run_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_run_id"], ["flow_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            name="uq_flow_step_attempts_run_step_attempt",
        ),
    )
    op.create_index(
        op.f("ix_flow_step_attempts_flow_id"),
        "flow_step_attempts",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_step_attempts_flow_run_id"),
        "flow_step_attempts",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_step_attempts_run_flow_step_attempt",
        "flow_step_attempts",
        ["flow_run_id", "flow_id", "step_id", "attempt_no"],
        unique=False,
    )
    op.create_index(
        "ix_flow_step_attempts_run_step_order_attempt",
        "flow_step_attempts",
        ["flow_run_id", "step_order", "attempt_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_step_attempts_tenant_id"),
        "flow_step_attempts",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_step_results",
        sa.Column("flow_run_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("assistant_id", sa.UUID(), nullable=True),
        sa.Column(
            "current_attempt_no", sa.Integer(), server_default="1", nullable=True
        ),
        sa.Column(
            "input_payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("effective_prompt", sa.String(), nullable=True),
        sa.Column(
            "output_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "model_parameters_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("num_tokens_input", sa.Integer(), nullable=True),
        sa.Column("num_tokens_output", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("flow_step_execution_hash", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','cancelled')",
            name="ck_flow_step_results_status",
        ),
        sa.CheckConstraint(
            "current_attempt_no IS NULL OR current_attempt_no >= 1",
            name="ck_flow_step_results_current_attempt_no_positive",
        ),
        sa.CheckConstraint(
            "step_order >= 1", name="ck_flow_step_results_step_order_positive"
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"], ["assistants.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_step_results_run_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_step_results_run_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_run_id"], ["flow_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id", "step_id", name="uq_flow_step_results_run_step"
        ),
    )
    op.create_index(
        "ix_flow_step_results_assistant_id",
        "flow_step_results",
        ["assistant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_step_results_flow_id"),
        "flow_step_results",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_step_results_flow_run_id"),
        "flow_step_results",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_step_results_run_flow_step",
        "flow_step_results",
        ["flow_run_id", "flow_id", "step_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_step_results_run_step_order",
        "flow_step_results",
        ["flow_run_id", "step_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_step_results_tenant_id"),
        "flow_step_results",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_steps",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("user_description", sa.String(), nullable=True),
        sa.Column(
            "input_source",
            sa.String(length=64),
            server_default="flow_input",
            nullable=False,
        ),
        sa.Column(
            "input_type", sa.String(length=32), server_default="any", nullable=False
        ),
        sa.Column(
            "input_contract", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "output_mode",
            sa.String(length=32),
            server_default="pass_through",
            nullable=False,
        ),
        sa.Column(
            "output_type", sa.String(length=32), server_default="text", nullable=False
        ),
        sa.Column(
            "output_contract", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "input_bindings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("output_classification_override", sa.Integer(), nullable=True),
        sa.Column(
            "input_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "output_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "review_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (input_type = 'text' AND output_mode = 'pass_through' AND output_type IN ('pdf','docx'))",
            name="ck_flow_steps_no_text_document_pass_through",
        ),
        sa.CheckConstraint(
            "input_source IN ('flow_input','previous_step','all_previous_steps','http_get')",
            name="ck_flow_steps_input_source",
        ),
        sa.CheckConstraint(
            "input_type IN ('text','json','image','audio','document','file','any')",
            name="ck_flow_steps_input_type",
        ),
        sa.CheckConstraint(
            "output_mode IN ('pass_through','compose_text','http_post','transcribe_only','template_fill','render_verbatim')",
            name="ck_flow_steps_output_mode",
        ),
        sa.CheckConstraint(
            "output_type IN ('text','json','pdf','docx')",
            name="ck_flow_steps_output_type",
        ),
        sa.CheckConstraint("step_order >= 1", name="ck_flow_steps_step_order_positive"),
        sa.CheckConstraint(
            "timeout_seconds IS NULL OR timeout_seconds > 0",
            name="ck_flow_steps_timeout_seconds_positive",
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"], ["assistants.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["flow_id", "tenant_id"],
            ["flows.id", "flows.tenant_id"],
            name="fk_flow_steps_flow_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_id", "id", name="uq_flow_steps_flow_id_id"),
        sa.UniqueConstraint(
            "flow_id", "step_order", name="uq_flow_steps_flow_step_order"
        ),
        sa.UniqueConstraint("id", "tenant_id", name="uq_flow_steps_id_tenant_id"),
    )
    op.create_index(
        "ix_flow_steps_assistant_id", "flow_steps", ["assistant_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_steps_flow_id"), "flow_steps", ["flow_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_steps_tenant_id"), "flow_steps", ["tenant_id"], unique=False
    )
    op.create_table(
        "flow_run_review_checkpoints",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("flow_run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.String(length=32),
            server_default="awaiting_review",
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "original_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "current_payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("step_label", sa.Text(), nullable=True),
        sa.Column("review_mode", sa.String(length=16), nullable=False),
        sa.Column("output_type", sa.String(length=32), nullable=False),
        sa.Column(
            "output_contract_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("requester_user_id", sa.UUID(), nullable=True),
        sa.Column("requester_service_id", sa.UUID(), nullable=True),
        sa.Column("requester_principal_type", sa.String(length=32), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_service_id", sa.UUID(), nullable=True),
        sa.Column("decided_by_principal_type", sa.String(length=32), nullable=True),
        sa.Column(
            "next_step_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("resume_idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(requester_principal_type = 'user' AND requester_user_id IS NOT NULL AND requester_service_id IS NULL) OR (requester_principal_type = 'service_key' AND requester_user_id IS NULL AND requester_service_id IS NOT NULL)",
            name="ck_flow_run_review_checkpoints_requester_principal",
        ),
        sa.CheckConstraint(
            "decided_by_principal_type IS NULL OR (decided_by_principal_type = 'user' AND decided_by_user_id IS NOT NULL AND decided_by_service_id IS NULL) OR (decided_by_principal_type = 'service_key' AND decided_by_user_id IS NULL AND decided_by_service_id IS NOT NULL)",
            name="ck_flow_run_review_checkpoints_decider_principal",
        ),
        sa.CheckConstraint(
            "output_type IN ('text','json','pdf','docx')",
            name="ck_flow_run_review_checkpoints_output_type",
        ),
        sa.CheckConstraint(
            "review_mode IN ('view','edit')",
            name="ck_flow_run_review_checkpoints_review_mode",
        ),
        sa.CheckConstraint(
            "state IN ('awaiting_review','edited','approved','rejected','resumed','cancelled','expired')",
            name="ck_flow_run_review_checkpoints_state",
        ),
        sa.CheckConstraint(
            "revision >= 1", name="ck_flow_run_review_checkpoints_revision"
        ),
        sa.CheckConstraint(
            "schema_version >= 1", name="ck_flow_run_review_checkpoints_schema_version"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_service_id"],
            ["service_principals.id"],
            name="fk_review_checkpoints_decided_by_service",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name="fk_review_checkpoints_decided_by_user",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name="fk_review_checkpoints_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_run_review_checkpoints_run_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "step_id", "attempt_no"],
            [
                "flow_step_attempts.flow_run_id",
                "flow_step_attempts.step_id",
                "flow_step_attempts.attempt_no",
            ],
            name="fk_flow_run_review_checkpoints_step_attempt",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_run_review_checkpoints_run_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_service_id"],
            ["service_principals.id"],
            name="fk_review_checkpoints_requester_service",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
            name="fk_review_checkpoints_requester_user",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_review_checkpoints_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            name="uq_flow_run_review_checkpoints_run_step_attempt",
        ),
    )
    op.create_index(
        op.f("ix_flow_run_review_checkpoints_flow_id"),
        "flow_run_review_checkpoints",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_review_checkpoints_flow_run_id"),
        "flow_run_review_checkpoints",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_review_checkpoints_run_step_attempt",
        "flow_run_review_checkpoints",
        ["flow_run_id", "step_id", "attempt_no"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_review_checkpoints_tenant_created_at",
        "flow_run_review_checkpoints",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_review_checkpoints_tenant_expires_at_reconcilable",
        "flow_run_review_checkpoints",
        ["tenant_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("state IN ('awaiting_review', 'edited')"),
    )
    op.create_index(
        op.f("ix_flow_run_review_checkpoints_tenant_id"),
        "flow_run_review_checkpoints",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "uq_flow_run_review_checkpoints_one_active_per_run",
        "flow_run_review_checkpoints",
        ["flow_run_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('awaiting_review', 'edited', 'approved')"),
    )
    op.create_index(
        "uq_flow_run_review_checkpoints_resume_key",
        "flow_run_review_checkpoints",
        ["tenant_id", "flow_run_id", "resume_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("resume_idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "flow_run_step_result_files",
        sa.Column("flow_run_id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("step_result_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('generated_output','declared_artifact')",
            name="ck_flow_run_step_result_files_source",
        ),
        sa.ForeignKeyConstraint(
            ["file_id", "tenant_id"],
            ["files.id", "files.tenant_id"],
            name="fk_flow_run_step_result_files_file_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_run_step_result_files_run_flow",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "step_id", "attempt_no"],
            [
                "flow_step_attempts.flow_run_id",
                "flow_step_attempts.step_id",
                "flow_step_attempts.attempt_no",
            ],
            name="fk_flow_run_step_result_files_step_attempt",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_run_step_result_files_run_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_result_id"], ["flow_step_results.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            "file_id",
            name="uq_flow_run_step_result_files_run_step_attempt_file",
        ),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            "ordinal",
            name="uq_flow_run_step_result_files_run_step_attempt_ordinal",
        ),
    )
    op.create_index(
        op.f("ix_flow_run_step_result_files_file_id"),
        "flow_run_step_result_files",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_result_files_flow_id"),
        "flow_run_step_result_files",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_result_files_flow_run_id"),
        "flow_run_step_result_files",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_result_files_run_step_attempt",
        "flow_run_step_result_files",
        ["flow_run_id", "step_id", "attempt_no"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_result_files_step_result",
        "flow_run_step_result_files",
        ["step_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_step_result_files_tenant_file",
        "flow_run_step_result_files",
        ["tenant_id", "file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_step_result_files_tenant_id"),
        "flow_run_step_result_files",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_run_webhook_deliveries",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("flow_run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload_ref", sa.String(length=255), nullable=False),
        sa.Column(
            "delivery_status",
            sa.String(length=32),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "delivery_attempts", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "next_delivery_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("claim_expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delivery_last_error", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((claim_token IS NULL AND claimed_at IS NULL AND claim_expires_at IS NULL) OR (delivery_status = 'pending' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL AND claim_expires_at IS NOT NULL))",
            name="ck_flow_run_webhook_deliveries_claim_shape",
        ),
        sa.CheckConstraint(
            "((delivery_status = 'pending' AND delivered_at IS NULL AND dead_lettered_at IS NULL) OR (delivery_status = 'delivered' AND delivered_at IS NOT NULL AND dead_lettered_at IS NULL) OR (delivery_status = 'dead_lettered' AND delivered_at IS NULL AND dead_lettered_at IS NOT NULL))",
            name="ck_flow_run_webhook_deliveries_delivery_timestamps",
        ),
        sa.CheckConstraint(
            "delivery_status IN ('pending','delivered','dead_lettered')",
            name="ck_flow_run_webhook_deliveries_status",
        ),
        sa.CheckConstraint(
            "idempotency_key <> ''",
            name="ck_flow_run_webhook_deliveries_idempotency_key",
        ),
        sa.CheckConstraint(
            "payload_ref <> ''", name="ck_flow_run_webhook_deliveries_payload_ref"
        ),
        sa.CheckConstraint(
            "attempt_no >= 1", name="ck_flow_run_webhook_deliveries_attempt_no"
        ),
        sa.CheckConstraint(
            "delivery_attempts >= 0",
            name="ck_flow_run_webhook_deliveries_delivery_attempts",
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_run_webhook_deliveries_run_flow",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "step_id", "attempt_no"],
            [
                "flow_step_attempts.flow_run_id",
                "flow_step_attempts.step_id",
                "flow_step_attempts.attempt_no",
            ],
            name="fk_flow_run_webhook_deliveries_step_attempt",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_run_webhook_deliveries_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_run_id",
            "step_id",
            "attempt_no",
            name="uq_flow_run_webhook_deliveries_attempt",
        ),
    )
    op.create_index(
        "ix_flow_run_webhook_deliveries_dead_lettered",
        "flow_run_webhook_deliveries",
        ["dead_lettered_at"],
        unique=False,
        postgresql_where=sa.text("delivery_status = 'dead_lettered'"),
    )
    op.create_index(
        op.f("ix_flow_run_webhook_deliveries_flow_id"),
        "flow_run_webhook_deliveries",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_webhook_deliveries_flow_run_id"),
        "flow_run_webhook_deliveries",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_webhook_deliveries_pending_delivery",
        "flow_run_webhook_deliveries",
        ["next_delivery_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.create_index(
        "ix_flow_run_webhook_deliveries_pending_run_tenant",
        "flow_run_webhook_deliveries",
        ["flow_run_id", "tenant_id"],
        unique=False,
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.create_index(
        "ix_flow_run_webhook_deliveries_tenant_created",
        "flow_run_webhook_deliveries",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_webhook_deliveries_tenant_id"),
        "flow_run_webhook_deliveries",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "flow_step_attempt_resolved_inputs",
        sa.Column("flow_step_attempt_id", sa.UUID(), nullable=False),
        sa.Column(
            "resolved_input_edges_jsonb",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "resolved_input_edge_count",
            sa.SmallInteger(),
            sa.Computed(
                "CASE WHEN jsonb_typeof(resolved_input_edges_jsonb) = 'object' AND jsonb_typeof(resolved_input_edges_jsonb -> 'edges') = 'array' THEN jsonb_array_length(resolved_input_edges_jsonb -> 'edges') ELSE -1 END",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolved_input_edge_count BETWEEN 0 AND 2048",
            name="ck_flow_step_attempt_resolved_input_count",
        ),
        sa.ForeignKeyConstraint(
            ["flow_step_attempt_id"], ["flow_step_attempts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("flow_step_attempt_id"),
    )
    op.create_table(
        "flow_provider_calls",
        sa.Column("flow_step_attempt_id", sa.UUID(), nullable=False),
        sa.Column("resolved_inputs_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("call_kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("request_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("provider_request_hash", sa.String(length=64), nullable=False),
        sa.Column("requested_model", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("response_format", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_capabilities",
            postgresql.ARRAY(sa.String(length=32)),
            nullable=False,
        ),
        sa.Column(
            "resolved_input_edge_indexes",
            postgresql.ARRAY(sa.SmallInteger()),
            nullable=False,
        ),
        sa.Column("call_reason", sa.String(length=32), nullable=False),
        sa.Column("mapped_execution_mode", sa.String(length=32), nullable=True),
        sa.Column("mapped_item_index", sa.Integer(), nullable=True),
        sa.Column("mapped_source_index", sa.Integer(), nullable=True),
        sa.Column("mapped_source_id", sa.Text(), nullable=True),
        sa.Column("response_model", sa.String(length=255), nullable=True),
        sa.Column("provider_response_id", sa.String(length=512), nullable=True),
        sa.Column("num_tokens_input", sa.Integer(), nullable=True),
        sa.Column("num_tokens_output", sa.Integer(), nullable=True),
        sa.Column("audio_seconds", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("input_source", sa.String(length=32), nullable=True),
        sa.Column("output_source", sa.String(length=32), nullable=True),
        sa.Column("outcome_reason", sa.String(length=64), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(('structured_output' = ANY(requested_capabilities)) = (response_format IN ('json_object', 'json_schema')))",
            name="ck_flow_provider_calls_capabilities_response_format",
        ),
        sa.CheckConstraint(
            "(call_kind = 'completion' AND audio_seconds IS NULL AND resolved_inputs_attempt_id = flow_step_attempt_id AND input_source IS DISTINCT FROM 'not_applicable' AND output_source IS DISTINCT FROM 'not_applicable') OR (call_kind = 'transcription' AND audio_seconds IS NOT NULL AND audio_seconds >= 0 AND resolved_inputs_attempt_id IS NULL AND cardinality(resolved_input_edge_indexes) = 0 AND response_format = 'none' AND cardinality(requested_capabilities) = 0 AND call_reason = 'initial' AND num_tokens_input IS NULL AND num_tokens_output IS NULL AND input_source IS NOT DISTINCT FROM   CASE WHEN status = 'completed' THEN 'not_applicable' END AND output_source IS NOT DISTINCT FROM   CASE WHEN status = 'completed' THEN 'not_applicable' END)",
            name="ck_flow_provider_calls_kind_shape",
        ),
        sa.CheckConstraint(
            "(cardinality(requested_capabilities) = 0 OR array_ndims(requested_capabilities) = 1) AND requested_capabilities <@ ARRAY['image_input','reasoning','structured_output','tool_calling']::varchar(32)[] AND cardinality(requested_capabilities) <= 4",
            name="ck_flow_provider_calls_capabilities_allowed",
        ),
        sa.CheckConstraint(
            "(input_source IS NULL AND num_tokens_input IS NULL) OR (input_source IN ('not_reported', 'not_applicable') AND num_tokens_input IS NULL) OR (input_source NOT IN ('not_reported', 'not_applicable') AND num_tokens_input IS NOT NULL)",
            name="ck_flow_provider_calls_input_usage_shape",
        ),
        sa.CheckConstraint(
            "(mapped_execution_mode IS NULL AND mapped_item_index IS NULL AND mapped_source_index IS NULL AND mapped_source_id IS NULL) OR (mapped_execution_mode = 'per_item' AND mapped_item_index >= 1 AND mapped_source_index IS NULL) OR (mapped_execution_mode = 'per_source' AND mapped_source_index >= 1 AND mapped_item_index IS NULL)",
            name="ck_flow_provider_calls_mapped_context",
        ),
        sa.CheckConstraint(
            "(output_source IS NULL AND num_tokens_output IS NULL) OR (output_source IN ('not_reported', 'not_applicable') AND num_tokens_output IS NULL) OR (output_source NOT IN ('not_reported', 'not_applicable') AND num_tokens_output IS NOT NULL)",
            name="ck_flow_provider_calls_output_usage_shape",
        ),
        sa.CheckConstraint(
            "(status = 'started' AND finished_at IS NULL AND outcome_reason IS NULL AND response_model IS NULL AND provider_response_id IS NULL AND num_tokens_input IS NULL AND num_tokens_output IS NULL AND input_source IS NULL AND output_source IS NULL) OR (status = 'completed' AND outcome_reason IS NULL AND input_source IS NOT NULL AND output_source IS NOT NULL AND finished_at IS NOT NULL) OR (status = 'rejected' AND finished_at IS NOT NULL AND outcome_reason IN ('response_format_rejected','provider_rejected') AND response_model IS NULL AND provider_response_id IS NULL AND num_tokens_input IS NULL AND num_tokens_output IS NULL AND input_source IS NULL AND output_source IS NULL) OR (status = 'outcome_unknown' AND finished_at IS NOT NULL AND outcome_reason IN ('request_timeout','run_cancelled','worker_interrupted','provider_error','request_cancelled','stale_started') AND response_model IS NULL AND provider_response_id IS NULL AND num_tokens_input IS NULL AND num_tokens_output IS NULL AND input_source IS NULL AND output_source IS NULL)",
            name="ck_flow_provider_calls_lifecycle_shape",
        ),
        sa.CheckConstraint(
            "call_kind IN ('completion','transcription')",
            name="ck_flow_provider_calls_kind",
        ),
        sa.CheckConstraint(
            "call_reason IN ('initial','response_format_fallback','tool_round')",
            name="ck_flow_provider_calls_reason",
        ),
        sa.CheckConstraint(
            "input_source IS NULL OR input_source IN ('provider','estimated','mixed','not_applicable','not_reported')",
            name="ck_flow_provider_calls_input_source",
        ),
        sa.CheckConstraint(
            "output_source IS NULL OR output_source IN ('provider','estimated','mixed','not_applicable','not_reported')",
            name="ck_flow_provider_calls_output_source",
        ),
        sa.CheckConstraint(
            "request_schema_version = 2 AND provider_request_hash ~ '^[0-9a-f]{64}$'",
            name="ck_flow_provider_calls_request_identity",
        ),
        sa.CheckConstraint(
            "response_format IN ('none','json_object','json_schema','other')",
            name="ck_flow_provider_calls_response_format",
        ),
        sa.CheckConstraint(
            "status IN ('started','completed','rejected','outcome_unknown')",
            name="ck_flow_provider_calls_status",
        ),
        sa.CheckConstraint(
            "(cardinality(resolved_input_edge_indexes) = 0 OR array_ndims(resolved_input_edge_indexes) = 1) AND array_position(resolved_input_edge_indexes, NULL) IS NULL AND cardinality(resolved_input_edge_indexes) <= 2048 AND 0 <= ALL(resolved_input_edge_indexes) AND 2048 > ALL(resolved_input_edge_indexes)",
            name="ck_flow_provider_calls_resolved_input_indexes",
        ),
        sa.CheckConstraint(
            "length(requested_model) > 0",
            name="ck_flow_provider_calls_requested_model_nonempty",
        ),
        sa.CheckConstraint(
            "num_tokens_input IS NULL OR num_tokens_input >= 0",
            name="ck_flow_provider_calls_input_tokens_nonnegative",
        ),
        sa.CheckConstraint(
            "num_tokens_output IS NULL OR num_tokens_output >= 0",
            name="ck_flow_provider_calls_output_tokens_nonnegative",
        ),
        sa.CheckConstraint(
            "ordinal >= 1", name="ck_flow_provider_calls_ordinal_positive"
        ),
        sa.CheckConstraint(
            "provider IS NULL OR length(provider) > 0",
            name="ck_flow_provider_calls_provider_nonempty",
        ),
        sa.ForeignKeyConstraint(
            ["flow_step_attempt_id"], ["flow_step_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_inputs_attempt_id"],
            ["flow_step_attempt_resolved_inputs.flow_step_attempt_id"],
            name="fk_flow_provider_calls_resolved_inputs",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "flow_step_attempt_id",
            "ordinal",
            name="uq_flow_provider_calls_attempt_ordinal",
        ),
    )
    op.create_index(
        "ix_flow_provider_calls_started_requested_at",
        "flow_provider_calls",
        ["requested_at"],
        unique=False,
        postgresql_where=sa.text("status = 'started'"),
    )
    op.create_table(
        "flow_run_audit_outbox",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("flow_run_id", sa.Uuid(), nullable=False),
        sa.Column("run_revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("review_checkpoint_id", sa.Uuid(), nullable=True),
        sa.Column("checkpoint_revision", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_api_key_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("target_status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "delivery_status",
            sa.String(length=32),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "delivery_attempts", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "next_delivery_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("delivered_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delivery_last_error", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((delivery_status = 'pending' AND delivered_at IS NULL AND dead_lettered_at IS NULL) OR (delivery_status = 'delivered' AND delivered_at IS NOT NULL AND dead_lettered_at IS NULL) OR (delivery_status = 'dead_lettered' AND delivered_at IS NULL AND dead_lettered_at IS NOT NULL))",
            name="ck_flow_run_audit_outbox_delivery_timestamps",
        ),
        sa.CheckConstraint(
            "delivery_status IN ('pending','delivered','dead_lettered')",
            name="ck_flow_run_audit_outbox_delivery_status",
        ),
        sa.CheckConstraint(
            "description = action || ':' || source",
            name="ck_flow_run_audit_outbox_description",
        ),
        sa.CheckConstraint(
            "source IN ('executor_completed','executor_failed','dispatch_failure','flow_deleted','definition_checksum_mismatch','invalid_flow_definition','assistant_snapshot_drift','step_missing','task_timeout','task_failure','missing_principal','stale_running_reconciler','user_cancel','review_rejected','review_checkpoint_opened','review_checkpoint_edited','review_checkpoint_approved','review_checkpoint_rejected','review_checkpoint_resumed','review_checkpoint_cancelled','review_expired','review_checkpoint_expired')",
            name="ck_flow_run_audit_outbox_source",
        ),
        sa.CheckConstraint(
            "target_status IN ('completed','failed','cancelled','awaiting_review','edited','approved','rejected','resumed','expired')",
            name="ck_flow_run_audit_outbox_target_status",
        ),
        sa.CheckConstraint(
            "((review_checkpoint_id IS NULL AND checkpoint_revision IS NULL) OR (review_checkpoint_id IS NOT NULL AND checkpoint_revision IS NOT NULL))",
            name="ck_flow_run_audit_outbox_checkpoint_key",
        ),
        sa.CheckConstraint(
            "delivery_attempts >= 0", name="ck_flow_run_audit_outbox_delivery_attempts"
        ),
        sa.ForeignKeyConstraint(
            ["actor_api_key_id"], ["api_keys_v2.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "flow_id"],
            ["flow_runs.id", "flow_runs.flow_id"],
            name="fk_flow_run_audit_outbox_run_flow",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_run_id", "tenant_id"],
            ["flow_runs.id", "flow_runs.tenant_id"],
            name="fk_flow_run_audit_outbox_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_checkpoint_id"],
            ["flow_run_review_checkpoints.id"],
            name="fk_flow_run_audit_outbox_review_checkpoint",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flow_run_audit_outbox_action",
        "flow_run_audit_outbox",
        ["action"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_audit_outbox_dead_lettered",
        "flow_run_audit_outbox",
        ["dead_lettered_at"],
        unique=False,
        postgresql_where=sa.text("delivery_status = 'dead_lettered'"),
    )
    op.create_index(
        op.f("ix_flow_run_audit_outbox_flow_id"),
        "flow_run_audit_outbox",
        ["flow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_audit_outbox_flow_run_id"),
        "flow_run_audit_outbox",
        ["flow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_audit_outbox_pending_delivery",
        "flow_run_audit_outbox",
        ["next_delivery_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.create_index(
        op.f("ix_flow_run_audit_outbox_review_checkpoint_id"),
        "flow_run_audit_outbox",
        ["review_checkpoint_id"],
        unique=False,
    )
    op.create_index(
        "ix_flow_run_audit_outbox_tenant_created",
        "flow_run_audit_outbox",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_run_audit_outbox_tenant_id"),
        "flow_run_audit_outbox",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "uq_flow_run_audit_outbox_checkpoint_revision",
        "flow_run_audit_outbox",
        ["review_checkpoint_id", "checkpoint_revision"],
        unique=True,
        postgresql_where=sa.text("review_checkpoint_id IS NOT NULL"),
    )
    op.create_index(
        "uq_flow_run_audit_outbox_run_revision",
        "flow_run_audit_outbox",
        ["flow_run_id", "run_revision"],
        unique=True,
        postgresql_where=sa.text("review_checkpoint_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_flows_published_version", "flows", type_="foreignkey")
    op.drop_index(
        "uq_flow_run_audit_outbox_run_revision",
        table_name="flow_run_audit_outbox",
        postgresql_where=sa.text("review_checkpoint_id IS NULL"),
    )
    op.drop_index(
        "uq_flow_run_audit_outbox_checkpoint_revision",
        table_name="flow_run_audit_outbox",
        postgresql_where=sa.text("review_checkpoint_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_flow_run_audit_outbox_tenant_id"), table_name="flow_run_audit_outbox"
    )
    op.drop_index(
        "ix_flow_run_audit_outbox_tenant_created", table_name="flow_run_audit_outbox"
    )
    op.drop_index(
        op.f("ix_flow_run_audit_outbox_review_checkpoint_id"),
        table_name="flow_run_audit_outbox",
    )
    op.drop_index(
        "ix_flow_run_audit_outbox_pending_delivery",
        table_name="flow_run_audit_outbox",
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_flow_run_audit_outbox_flow_run_id"), table_name="flow_run_audit_outbox"
    )
    op.drop_index(
        op.f("ix_flow_run_audit_outbox_flow_id"), table_name="flow_run_audit_outbox"
    )
    op.drop_index(
        "ix_flow_run_audit_outbox_dead_lettered",
        table_name="flow_run_audit_outbox",
        postgresql_where=sa.text("delivery_status = 'dead_lettered'"),
    )
    op.drop_index("ix_flow_run_audit_outbox_action", table_name="flow_run_audit_outbox")
    op.drop_table("flow_run_audit_outbox")
    op.drop_index(
        "ix_flow_provider_calls_started_requested_at",
        table_name="flow_provider_calls",
        postgresql_where=sa.text("status = 'started'"),
    )
    op.drop_table("flow_provider_calls")
    op.drop_table("flow_step_attempt_resolved_inputs")
    op.drop_index(
        op.f("ix_flow_run_webhook_deliveries_tenant_id"),
        table_name="flow_run_webhook_deliveries",
    )
    op.drop_index(
        "ix_flow_run_webhook_deliveries_tenant_created",
        table_name="flow_run_webhook_deliveries",
    )
    op.drop_index(
        "ix_flow_run_webhook_deliveries_pending_run_tenant",
        table_name="flow_run_webhook_deliveries",
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.drop_index(
        "ix_flow_run_webhook_deliveries_pending_delivery",
        table_name="flow_run_webhook_deliveries",
        postgresql_where=sa.text("delivery_status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_flow_run_webhook_deliveries_flow_run_id"),
        table_name="flow_run_webhook_deliveries",
    )
    op.drop_index(
        op.f("ix_flow_run_webhook_deliveries_flow_id"),
        table_name="flow_run_webhook_deliveries",
    )
    op.drop_index(
        "ix_flow_run_webhook_deliveries_dead_lettered",
        table_name="flow_run_webhook_deliveries",
        postgresql_where=sa.text("delivery_status = 'dead_lettered'"),
    )
    op.drop_table("flow_run_webhook_deliveries")
    op.drop_index(
        op.f("ix_flow_run_step_result_files_tenant_id"),
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        "ix_flow_run_step_result_files_tenant_file",
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        "ix_flow_run_step_result_files_step_result",
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        "ix_flow_run_step_result_files_run_step_attempt",
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        op.f("ix_flow_run_step_result_files_flow_run_id"),
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        op.f("ix_flow_run_step_result_files_flow_id"),
        table_name="flow_run_step_result_files",
    )
    op.drop_index(
        op.f("ix_flow_run_step_result_files_file_id"),
        table_name="flow_run_step_result_files",
    )
    op.drop_table("flow_run_step_result_files")
    op.drop_index(
        "uq_flow_run_review_checkpoints_resume_key",
        table_name="flow_run_review_checkpoints",
        postgresql_where=sa.text("resume_idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_flow_run_review_checkpoints_one_active_per_run",
        table_name="flow_run_review_checkpoints",
        postgresql_where=sa.text("state IN ('awaiting_review', 'edited', 'approved')"),
    )
    op.drop_index(
        op.f("ix_flow_run_review_checkpoints_tenant_id"),
        table_name="flow_run_review_checkpoints",
    )
    op.drop_index(
        "ix_flow_run_review_checkpoints_tenant_expires_at_reconcilable",
        table_name="flow_run_review_checkpoints",
        postgresql_where=sa.text("state IN ('awaiting_review', 'edited')"),
    )
    op.drop_index(
        "ix_flow_run_review_checkpoints_tenant_created_at",
        table_name="flow_run_review_checkpoints",
    )
    op.drop_index(
        "ix_flow_run_review_checkpoints_run_step_attempt",
        table_name="flow_run_review_checkpoints",
    )
    op.drop_index(
        op.f("ix_flow_run_review_checkpoints_flow_run_id"),
        table_name="flow_run_review_checkpoints",
    )
    op.drop_index(
        op.f("ix_flow_run_review_checkpoints_flow_id"),
        table_name="flow_run_review_checkpoints",
    )
    op.drop_table("flow_run_review_checkpoints")
    op.drop_index(op.f("ix_flow_steps_tenant_id"), table_name="flow_steps")
    op.drop_index(op.f("ix_flow_steps_flow_id"), table_name="flow_steps")
    op.drop_index("ix_flow_steps_assistant_id", table_name="flow_steps")
    op.drop_table("flow_steps")
    op.drop_index(
        op.f("ix_flow_step_results_tenant_id"), table_name="flow_step_results"
    )
    op.drop_index("ix_flow_step_results_run_step_order", table_name="flow_step_results")
    op.drop_index("ix_flow_step_results_run_flow_step", table_name="flow_step_results")
    op.drop_index(
        op.f("ix_flow_step_results_flow_run_id"), table_name="flow_step_results"
    )
    op.drop_index(op.f("ix_flow_step_results_flow_id"), table_name="flow_step_results")
    op.drop_index("ix_flow_step_results_assistant_id", table_name="flow_step_results")
    op.drop_table("flow_step_results")
    op.drop_index(
        op.f("ix_flow_step_attempts_tenant_id"), table_name="flow_step_attempts"
    )
    op.drop_index(
        "ix_flow_step_attempts_run_step_order_attempt", table_name="flow_step_attempts"
    )
    op.drop_index(
        "ix_flow_step_attempts_run_flow_step_attempt", table_name="flow_step_attempts"
    )
    op.drop_index(
        op.f("ix_flow_step_attempts_flow_run_id"), table_name="flow_step_attempts"
    )
    op.drop_index(
        op.f("ix_flow_step_attempts_flow_id"), table_name="flow_step_attempts"
    )
    op.drop_table("flow_step_attempts")
    op.drop_index(
        op.f("ix_flow_run_step_input_files_tenant_id"),
        table_name="flow_run_step_input_files",
    )
    op.drop_index(
        "ix_flow_run_step_input_files_tenant_file",
        table_name="flow_run_step_input_files",
    )
    op.drop_index(
        "ix_flow_run_step_input_files_run_step_attempt",
        table_name="flow_run_step_input_files",
    )
    op.drop_index(
        "ix_flow_run_step_input_files_flow_step", table_name="flow_run_step_input_files"
    )
    op.drop_index(
        op.f("ix_flow_run_step_input_files_flow_run_id"),
        table_name="flow_run_step_input_files",
    )
    op.drop_index(
        op.f("ix_flow_run_step_input_files_flow_id"),
        table_name="flow_run_step_input_files",
    )
    op.drop_index(
        op.f("ix_flow_run_step_input_files_file_id"),
        table_name="flow_run_step_input_files",
    )
    op.drop_table("flow_run_step_input_files")
    op.drop_index(
        op.f("ix_flow_template_assets_tenant_id"), table_name="flow_template_assets"
    )
    op.drop_index(
        op.f("ix_flow_template_assets_space_id"), table_name="flow_template_assets"
    )
    op.drop_index(
        op.f("ix_flow_template_assets_flow_id"), table_name="flow_template_assets"
    )
    op.drop_index(
        "ix_flow_template_assets_flow_active",
        table_name="flow_template_assets",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_flow_template_assets_file_id"), table_name="flow_template_assets"
    )
    op.drop_table("flow_template_assets")
    op.drop_index(
        "ix_flow_runtime_uploaded_files_user_owner",
        table_name="flow_runtime_uploaded_files",
        postgresql_where=sa.text("owner_type = 'user'"),
    )
    op.drop_index(
        op.f("ix_flow_runtime_uploaded_files_tenant_id"),
        table_name="flow_runtime_uploaded_files",
    )
    op.drop_index(
        "ix_flow_runtime_uploaded_files_service_owner",
        table_name="flow_runtime_uploaded_files",
        postgresql_where=sa.text("owner_type = 'service_key'"),
    )
    op.drop_index(
        op.f("ix_flow_runtime_uploaded_files_flow_id"),
        table_name="flow_runtime_uploaded_files",
    )
    op.drop_table("flow_runtime_uploaded_files")
    op.drop_index(
        "uq_flow_runs_idempotency_user_key",
        table_name="flow_runs",
        postgresql_where=sa.text(
            "principal_type = 'user' AND idempotency_key IS NOT NULL"
        ),
    )
    op.drop_index(
        "uq_flow_runs_idempotency_service_key",
        table_name="flow_runs",
        postgresql_where=sa.text(
            "principal_type = 'service_key' AND idempotency_key IS NOT NULL"
        ),
    )
    op.drop_index(op.f("ix_flow_runs_trace_id"), table_name="flow_runs")
    op.drop_index(
        "ix_flow_runs_terminal_retention_anchor",
        table_name="flow_runs",
        postgresql_include=("flow_id",),
        postgresql_where=sa.text("status IN ('completed', 'failed', 'cancelled')"),
    )
    op.drop_index(op.f("ix_flow_runs_tenant_id"), table_name="flow_runs")
    op.drop_index("ix_flow_runs_tenant_created_at", table_name="flow_runs")
    op.drop_index(op.f("ix_flow_runs_status"), table_name="flow_runs")
    op.drop_index(
        "ix_flow_runs_service_principal_created_at",
        table_name="flow_runs",
        postgresql_where=sa.text("principal_type = 'service_key'"),
    )
    op.drop_index(
        "ix_flow_runs_running_updated_at",
        table_name="flow_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_flow_runs_queued_dispatch_due",
        table_name="flow_runs",
        postgresql_where=sa.text(
            "status = 'queued' AND dispatch_next_attempt_at IS NOT NULL AND dispatch_exhausted_at IS NULL"
        ),
    )
    op.drop_index("ix_flow_runs_job_id", table_name="flow_runs")
    op.drop_index("ix_flow_runs_flow_id_status", table_name="flow_runs")
    op.drop_index(op.f("ix_flow_runs_flow_id"), table_name="flow_runs")
    op.drop_table("flow_runs")
    op.drop_index(
        "ix_provider_token_usages_tenant_occurred", table_name="provider_token_usages"
    )
    op.drop_index(
        "ix_provider_token_usages_completion_model_id",
        table_name="provider_token_usages",
    )
    op.drop_table("provider_token_usages")
    op.drop_index(
        op.f("ix_flow_resource_bindings_tenant_id"), table_name="flow_resource_bindings"
    )
    op.drop_index(
        "ix_flow_resource_bindings_tenant_flow", table_name="flow_resource_bindings"
    )
    op.drop_index(
        op.f("ix_flow_resource_bindings_space_id"), table_name="flow_resource_bindings"
    )
    op.drop_index(
        "ix_flow_resource_bindings_local_target", table_name="flow_resource_bindings"
    )
    op.drop_index(
        op.f("ix_flow_resource_bindings_flow_id"), table_name="flow_resource_bindings"
    )
    op.drop_table("flow_resource_bindings")
    op.drop_index(
        "ix_flow_package_imports_tenant_space_created",
        table_name="flow_package_imports",
    )
    op.drop_index(
        op.f("ix_flow_package_imports_tenant_id"), table_name="flow_package_imports"
    )
    op.drop_index(
        op.f("ix_flow_package_imports_space_id"), table_name="flow_package_imports"
    )
    op.drop_index(
        "ix_flow_package_imports_space_checksum_created",
        table_name="flow_package_imports",
    )
    op.drop_index(
        op.f("ix_flow_package_imports_flow_id"), table_name="flow_package_imports"
    )
    op.drop_table("flow_package_imports")
    op.drop_index("ix_service_principals_tenant_id", table_name="service_principals")
    op.drop_table("service_principals")
    op.drop_index(op.f("ix_flow_versions_tenant_id"), table_name="flow_versions")
    op.drop_table("flow_versions")
    op.drop_index(
        "uq_flows_space_id_name_active",
        table_name="flows",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_flows_tenant_id"), table_name="flows")
    op.drop_index(op.f("ix_flows_space_id"), table_name="flows")
    op.drop_index("ix_flows_space_deleted", table_name="flows")
    op.drop_table("flows")
    op.drop_constraint("uq_files_id_tenant_id", "files", type_="unique")
    # ### end Alembic commands ###
