"""Admission checks for documents a tool generated (DOCX, XLSX, PDF, CSV).

A generated document is untrusted provider output that Eneo will store and
offer for download. Before it becomes a File its bytes must match the declared
type and must not carry active or externally loading content. The checks read
structure only (the zip central directory, bounded package parts, PDF names);
nothing is rendered or executed.
"""

from __future__ import annotations

import io
import re
import zipfile

from eneo.mcp_servers.domain.entities.mcp_server import (
    CSV_MIME_TYPE,
    DOCX_MIME_TYPE,
    PDF_MIME_TYPE,
    XLSX_MIME_TYPE,
)

# Same bounds as attachment intake: a document declaring more expansion than
# this is a decompression bomb, not a report.
_MAX_UNCOMPRESSED_BYTES = 64 * 1024 * 1024
_MAX_COMPRESSION_RATIO = 100
_MAX_ENTRIES = 10_000
# Package parts read for inspection ([Content_Types].xml, *.rels) are small.
_MAX_PART_BYTES = 1024 * 1024

_REQUIRED_PART = {
    DOCX_MIME_TYPE: "word/document.xml",
    XLSX_MIME_TYPE: "xl/workbook.xml",
}
# Macros, ActiveX, embedded OLE objects and workbook links to other files.
_FORBIDDEN_PART = re.compile(
    r"(^|/)(vbaProject\.bin|vbaData\.xml)$|(^|/)(activeX|embeddings|externalLinks)/",
    re.IGNORECASE,
)
# Relationship types that fetch or run something when the file is opened.
# Hyperlinks are external by nature and stay allowed.
_EXTERNAL_TARGET = re.compile(rb'TargetMode\s*=\s*"External"', re.IGNORECASE)
_HYPERLINK_RELATIONSHIP = re.compile(rb"/relationships/hyperlink\"", re.IGNORECASE)
_RELATIONSHIP = re.compile(rb"<Relationship\b[^>]*>", re.IGNORECASE)
# PDF names that run script, launch programs or carry embedded files.
_PDF_ACTIVE_CONTENT = re.compile(
    rb"/(JavaScript|JS|Launch|EmbeddedFiles?|RichMedia|XFA)\b"
)


class GeneratedDocumentRejected(ValueError):
    """The generated bytes are not an acceptable document of the declared type."""


def validate_generated_document(data: bytes, mime_type: str) -> None:
    """Raise ``GeneratedDocumentRejected`` unless ``data`` is a safe ``mime_type``."""
    if mime_type == PDF_MIME_TYPE:
        _validate_pdf(data)
    elif mime_type == CSV_MIME_TYPE:
        _validate_csv(data)
    elif mime_type in _REQUIRED_PART:
        _validate_ooxml(data, _REQUIRED_PART[mime_type])
    else:
        raise GeneratedDocumentRejected(f"Unsupported document type {mime_type!r}")


def _validate_pdf(data: bytes) -> None:
    if not data.startswith(b"%PDF-") or b"%%EOF" not in data[-2048:]:
        raise GeneratedDocumentRejected("Not a complete PDF document")
    # Names inside compressed object streams are not visible here; the
    # bundled renderer does not emit them, and a provider hiding them is out
    # of scope for a structural check.
    if _PDF_ACTIVE_CONTENT.search(data):
        raise GeneratedDocumentRejected("PDF contains active content")


def _validate_csv(data: bytes) -> None:
    # Values stay exactly as produced (a leading "=" or "-" is data here);
    # spreadsheet formula injection is the concern of whoever opens the file
    # in a spreadsheet, and Eneo's own spreadsheet renderer keeps text as text.
    if not data or b"\x00" in data:
        raise GeneratedDocumentRejected("Not a text CSV file")
    try:
        data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise GeneratedDocumentRejected("CSV files must use UTF-8") from exc


def _validate_ooxml(data: bytes, required_part: str) -> None:
    try:
        archive = zipfile.ZipFile(io.BytesIO(data))
    except zipfile.BadZipFile as exc:
        raise GeneratedDocumentRejected("Not an Office Open XML package") from exc
    with archive:
        entries = archive.infolist()
        if len(entries) > _MAX_ENTRIES:
            raise GeneratedDocumentRejected("Package has too many parts")
        expanded = sum(entry.file_size for entry in entries)
        if expanded > min(
            _MAX_UNCOMPRESSED_BYTES, max(len(data) * _MAX_COMPRESSION_RATIO, 1)
        ):
            raise GeneratedDocumentRejected("Package expands beyond the size limit")
        names = {entry.filename for entry in entries}
        for name in names:
            if (
                name.startswith(("/", "\\"))
                or "\\" in name
                or ".." in name.split("/")
                or ":" in name
            ):
                raise GeneratedDocumentRejected("Package part has an unsafe path")
            if _FORBIDDEN_PART.search(name):
                raise GeneratedDocumentRejected(
                    "Package contains macros, embedded objects or external links"
                )
        if "[Content_Types].xml" not in names or required_part not in names:
            raise GeneratedDocumentRejected("Package is not the declared document type")
        content_types = _read_part(archive, "[Content_Types].xml")
        if b"macroEnabled" in content_types or b"vbaProject" in content_types:
            raise GeneratedDocumentRejected("Package declares macros")
        for name in names:
            if not name.endswith(".rels"):
                continue
            for relationship in _RELATIONSHIP.findall(_read_part(archive, name)):
                if _EXTERNAL_TARGET.search(
                    relationship
                ) and not _HYPERLINK_RELATIONSHIP.search(relationship):
                    raise GeneratedDocumentRejected(
                        "Package loads external content when opened"
                    )


def _read_part(archive: zipfile.ZipFile, name: str) -> bytes:
    info = archive.getinfo(name)
    if info.file_size > _MAX_PART_BYTES:
        raise GeneratedDocumentRejected(f"Package part {name} is too large")
    with archive.open(info) as part:
        return part.read(_MAX_PART_BYTES + 1)
