import { describe, expect, test, vi } from "vitest";
import { get } from "svelte/store";

// Critical test #4 (PRD "Critical tests"): "Apply to instructions" must go
// through the *same* save path a manual edit uses — onApply only writes the
// produced prompt into local editor state ($update.prompt.text), and the
// normal Save button then persists it via a single intric.assistants.update().
// No parallel apply-and-save path, so Apply + Save produces the same row count
// (one new prompt version) as typing into the prompt field + Save.
//
// The save path under test (createResourceEditor, wired in AssistantEditor.ts)
// reaches for the Svelte component lifecycle (setContext) and a toast component
// on error. Neither is relevant to the parity assertion, so they are stubbed to
// keep this a pure-logic test, matching the repo's co-located .test.ts pattern.
vi.mock("$lib/core/context", () => ({
  createContext: () => [() => undefined, () => undefined]
}));
vi.mock("$lib/core/errors", () => ({ toastError: () => undefined }));

import { initAssistantEditor } from "$lib/features/assistants/AssistantEditor";
import type { Assistant, Intric } from "@intric/intric-js";

const APPLIED_TEXT = "You are a meticulous research assistant. Cite every source.";

function makeAssistant(): Assistant {
  // Minimal shape the editor cares about: an id plus a populated prompt so the
  // applied/manual text replaces a real existing value (mirrors an assistant
  // that already has instructions).
  return {
    id: "assistant-1",
    name: "Test assistant",
    prompt: { id: "prompt-1", text: "Original instructions", description: "" }
  } as unknown as Assistant;
}

function makeEditor() {
  const updateSpy = vi.fn(async ({ assistant, update }) => ({ ...assistant, ...update }));
  const intric = { assistants: { update: updateSpy } } as unknown as Intric;
  const editor = initAssistantEditor({ assistant: makeAssistant(), intric });
  return { editor, updateSpy };
}

describe("Prompt Guide Apply flow (critical test #4)", () => {
  test("Apply mutates local state only; Save persists it via one assistants.update()", async () => {
    const { editor, updateSpy } = makeEditor();
    const { update, currentChanges } = editor.state;

    // Starting state mirrors the persisted assistant.
    expect(get(update).prompt.text).toBe("Original instructions");

    // Simulate the Prompt Guide modal firing onApply("..."). The edit page's
    // handler only writes into $update.prompt.text (+ a source description);
    // it does not call intric.assistants.update.
    update.update((u) => {
      u.prompt.text = APPLIED_TEXT;
      u.prompt.description = "Generated by Prompt Guide on 2026-01-01 12:00";
      return u;
    });

    // Apply must not hit the network — there is no parallel apply-and-save path.
    expect(updateSpy).not.toHaveBeenCalled();
    expect(get(update).prompt.text).toBe(APPLIED_TEXT);
    expect(get(currentChanges).hasUnsavedChanges).toBe(true);

    // Now the user clicks the normal Save button.
    await editor.saveChanges();

    // Save goes through the same endpoint a manual edit would, exactly once,
    // carrying the applied prompt text in the PATCH payload.
    expect(updateSpy).toHaveBeenCalledTimes(1);
    const payload = updateSpy.mock.calls[0][0] as {
      assistant: { id: string };
      update: { prompt: { text: string } };
    };
    expect(payload.assistant.id).toBe("assistant-1");
    expect(payload.update.prompt.text).toBe(APPLIED_TEXT);
  });

  test("A manual prompt edit + Save produces the identical update() call (row-count parity)", async () => {
    const { editor, updateSpy } = makeEditor();
    const { update } = editor.state;

    // A manual edit is just typing into the prompt field: same local mutation,
    // same Save, same single update() call as the Apply path above.
    update.update((u) => {
      u.prompt.text = APPLIED_TEXT;
      return u;
    });
    await editor.saveChanges();

    expect(updateSpy).toHaveBeenCalledTimes(1);
    const payload = updateSpy.mock.calls[0][0] as { update: { prompt: { text: string } } };
    expect(payload.update.prompt.text).toBe(APPLIED_TEXT);
  });
});
