from __future__ import annotations

INPUT_ROLE_MARKERS: tuple[str, ...] = (
    "ladda upp",
    "laddar upp",
    "upload",
    "skicka in",
    "send in",
    "ta emot",
    "tar emot",
    "skriver en fråga",
    "skriv en fråga",
    "write a question",
    "writes a question",
    "receive",
    "attach",
    "bifoga",
    "bifogade",
    "lämna in",
    "lämnar in",
    "uppladdad",
    "uppladdat",
    "uppladdade",
    "uploaded",
    "vid körning",
    "runtime input",
)

OUTPUT_ROLE_MARKERS: tuple[str, ...] = (
    "generera",
    "genererar",
    "generate",
    "returnera",
    "returnerar",
    "return",
    "leverera",
    "levererar",
    "deliver",
    "skapa",
    "skapar",
    "create",
    "producera",
    "producerar",
    "produce",
    "få tillbaka",
    "få ut",
    "få en",
    "få ett",
    "get a",
    "get an",
    "get back",
    "skriv",
    "skriver",
    "write",
    "fyll",
    "fyller",
    "fyll i",
    "fill",
    "fills",
    "fill in",
    "slutresultatet",
    "final output",
)

REPLACEMENT_PHRASES: tuple[str, ...] = (
    "i stället för",
    "istället för",
    "instead of",
)
