from importlib import import_module

_TABLE_MODULES = (
    "intric.database.tables.ai_models_table",
    "intric.database.tables.allowed_origins_table",
    "intric.database.tables.api_keys_table",
    "intric.database.tables.api_keys_v2_table",
    "intric.database.tables.audit_action_config_table",
    "intric.database.tables.audit_category_config_table",
    "intric.database.tables.audit_log_table",
    "intric.database.tables.audit_retention_policy_table",
    "intric.database.tables.app_table",
    "intric.database.tables.app_template_table",
    "intric.database.tables.assistant_table",
    "intric.database.tables.assistant_template_table",
    "intric.database.tables.collections_table",
    "intric.database.tables.completion_model_migration_history_table",
    "intric.database.tables.feature_flag_table",
    "intric.database.tables.files_table",
    "intric.database.tables.group_chats_table",
    "intric.database.tables.groups_spaces_table",
    "intric.database.tables.help_assistant_assignment_history_table",
    "intric.database.tables.help_assistant_runs_table",
    "intric.database.tables.icons_table",
    "intric.database.tables.info_blob_chunk_table",
    "intric.database.tables.info_blobs_table",
    "intric.database.tables.integration_table",
    "intric.database.tables.job_table",
    "intric.database.tables.logging_table",
    "intric.database.tables.module_table",
    "intric.database.tables.org_space_assistant_roles_table",
    "intric.database.tables.prompts_table",
    "intric.database.tables.questions_table",
    "intric.database.tables.roles_table",
    "intric.database.tables.service_table",
    "intric.database.tables.sessions_table",
    "intric.database.tables.settings_table",
    "intric.database.tables.sharepoint_subscription_table",
    "intric.database.tables.spaces_table",
    "intric.database.tables.sync_log_table",
    "intric.database.tables.tenant_sharepoint_app_table",
    "intric.database.tables.tenant_table",
    "intric.database.tables.user_groups_table",
    "intric.database.tables.users_table",
    "intric.database.tables.web_search_results_table",
    "intric.database.tables.websites_spaces_table",
    "intric.database.tables.websites_table",
    "intric.database.tables.widget_table",
    "intric.database.tables.workflow_tables",
)

for module_name in _TABLE_MODULES:
    import_module(module_name)
